force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Please select category which best corresponds with this case.</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Department__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>5500</fullName>
            </value>
            <value>
                <fullName>Billing, Commissions, and Fees</fullName>
            </value>
            <value>
                <fullName>Contribution and Payroll</fullName>
            </value>
            <value>
                <fullName>DIrect Integration (SFTP)</fullName>
            </value>
            <value>
                <fullName>Distribution</fullName>
            </value>
            <value>
                <fullName>Document Request</fullName>
            </value>
            <value>
                <fullName>General Question</fullName>
            </value>
            <value>
                <fullName>Investments</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Login Issues</fullName>
            </value>
            <value>
                <fullName>New Comp</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Plan Compliance</fullName>
            </value>
            <value>
                <fullName>Plan Correction</fullName>
            </value>
            <value>
                <fullName>Plan Update</fullName>
            </value>
            <value>
                <fullName>Report Request</fullName>
            </value>
            <value>
                <fullName>Rollover In</fullName>
            </value>
            <value>
                <fullName>Sales Inquiry</fullName>
            </value>
            <value>
                <fullName>SingleK</fullName>
            </value>
            <value>
                <fullName>Transition</fullName>
            </value>
            <value>
                <fullName>User Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Expected_Days_to_Close__c.field-meta.xml
<CustomField>
    <fullName>Expected_Days_to_Close__c</fullName>
    <description>Calculated from case&apos;s SLA and communicated to clients when case is transferred to an ops team (Compliance, Payroll, R&amp;W, A&amp;F).</description>
    <label>Expected Days to Close</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Goal_Close_DT_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Goal_Close_DT_Stamp__c</fullName>
    <label>Goal Close DT Stamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Goal_FR_DT_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Goal_FR_DT_Stamp__c</fullName>
    <label>Goal FR DT Stamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Compliance.recordType-meta.xml
<RecordType>
    <fullName>Compliance</fullName>
    <active>true</active>
    <businessProcess>Servicing</businessProcess>
    <label>Compliance Cases</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Servicing.recordType-meta.xml
<RecordType>
    <fullName>Servicing</fullName>
    <active>true</active>
    <businessProcess>Servicing</businessProcess>
    <description>Used by Servicing Teams</description>
    <label>Servicing</label>
</RecordType>

force-app/main/default/objects/Project_Deliverables__c/Project_Deliverables__c.object-meta.xml
<CustomObject>
    <label>Project Deliverable</label>
    <nameField>
        <label>Project Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Deliverables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Deliverables__c/fields/Case_Close_Time_Hours__c.field-meta.xml
<CustomField>
    <fullName>Case_Close_Time_Hours__c</fullName>
    <label>Case Close Time Hours</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Deliverables__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1099</fullName>
                <isActive>false</isActive>
                <label>1099</label>
            </value>
            <value>
                <fullName>1099 Corrections</fullName>
                <isActive>false</isActive>
                <label>1099 Corrections</label>
            </value>
            <value>
                <fullName>2FA</fullName>
                <isActive>false</isActive>
                <label>2FA</label>
            </value>
            <value>
                <fullName>3(16)</fullName>
                <isActive>false</isActive>
                <label>3(16)</label>
            </value>
            <value>
                <fullName>402(g)</fullName>
                <isActive>false</isActive>
                <label>402(g)</label>
            </value>
            <value>
                <fullName>5500</fullName>
            </value>
            <value>
                <fullName>Abandoned Plan Review</fullName>
                <isActive>false</isActive>
                <label>Abandoned Plan Review</label>
            </value>
            <value>
                <fullName>Account/Contact Information Change</fullName>
                <isActive>false</isActive>
                <label>Account/Contact Information Change</label>
            </value>
            <value>
                <fullName>Account Setup/Update</fullName>
                <isActive>false</isActive>
                <label>Account Setup/Update</label>
            </value>
            <value>
                <fullName>ACH</fullName>
                <isActive>false</isActive>
                <label>ACH</label>
            </value>
            <value>
                <fullName>Acquisition Merger Survey</fullName>
                <isActive>false</isActive>
                <label>Acquisition Merger Survey</label>
            </value>
            <value>
                <fullName>Add/Remove User</fullName>
                <isActive>false</isActive>
                <label>Add/Remove User</label>
            </value>
            <value>
                <fullName>Address Change</fullName>
                <isActive>false</isActive>
                <label>Address Change</label>
            </value>
            <value>
                <fullName>Address Look-Up</fullName>
                <isActive>false</isActive>
                <label>Address Look-Up</label>
            </value>
            <value>
                <fullName>Adjustments</fullName>
                <isActive>false</isActive>
                <label>Adjustments</label>
            </value>
            <value>
                <fullName>Administrative Requests</fullName>
                <isActive>false</isActive>
                <label>Administrative Requests</label>
            </value>
            <value>
                <fullName>ADP/ACP Annual Testing</fullName>
                <isActive>false</isActive>
                <label>ADP/ACP Annual Testing</label>
            </value>
            <value>
                <fullName>ADP ACP Refund</fullName>
                <isActive>false</isActive>
                <label>ADP ACP Refund</label>
            </value>
            <value>
                <fullName>Advisor</fullName>
                <isActive>false</isActive>
                <label>Advisor</label>
            </value>
            <value>
                <fullName>Advisor Payments</fullName>
                <isActive>false</isActive>
                <label>Advisor Payments</label>
            </value>
            <value>
                <fullName>Advisor set up</fullName>
                <isActive>false</isActive>
                <label>Advisor set up</label>
            </value>
            <value>
                <fullName>Amending plan</fullName>
                <isActive>false</isActive>
                <label>Amending plan</label>
            </value>
            <value>
                <fullName>Amendments</fullName>
                <isActive>false</isActive>
                <label>Amendments</label>
            </value>
            <value>
                <fullName>Ancillary Billing</fullName>
                <isActive>false</isActive>
                <label>Ancillary Billing</label>
            </value>
            <value>
                <fullName>Annual Compliance Testing</fullName>
                <isActive>false</isActive>
                <label>Annual Compliance Testing</label>
            </value>
            <value>
                <fullName>AP Invoices &amp; Inquiries</fullName>
                <isActive>false</isActive>
                <label>AP Invoices &amp; Inquiries</label>
            </value>
            <value>
                <fullName>ASC Updates</fullName>
                <isActive>false</isActive>
                <label>ASC Updates</label>
            </value>
            <value>
                <fullName>Audit</fullName>
                <isActive>false</isActive>
                <label>Audit</label>
            </value>
            <value>
                <fullName>Audit Research/Confirmations</fullName>
                <isActive>false</isActive>
                <label>Audit Research/Confirmations</label>
            </value>
            <value>
                <fullName>Auto Enroll</fullName>
                <isActive>false</isActive>
                <label>Auto Enroll</label>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>New Comp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Deliverables__c/fields/First_Response_Time_Hours__c.field-meta.xml
<CustomField>
    <fullName>First_Response_Time_Hours__c</fullName>
    <label>First Response Time Hours</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Deliverables__c/fields/Work_Breakdown_Structure__c.field-meta.xml
<CustomField>
    <fullName>Work_Breakdown_Structure__c</fullName>
    <label>Work Breakdown Structure</label>
    <referenceTo>Work_Breakdown_Structure__c</referenceTo>
    <relationshipLabel>Project Deliverables</relationshipLabel>
    <relationshipName>Project_Deliverables</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Deliverables__c/recordTypes/Case_Deliverable.recordType-meta.xml
<RecordType>
    <fullName>Case_Deliverable</fullName>
    <active>true</active>
    <label>Case Deliverable</label>
</RecordType>

force-app/main/default/objects/Work_Breakdown_Structure__c/Work_Breakdown_Structure__c.object-meta.xml
<CustomObject>
    <label>Work Breakdown Structure</label>
    <nameField>
        <label>Work Breakdown Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Breakdown Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Breakdown_Structure__c/fields/Case_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Record_Type__c</fullName>
    <label>Case Record Type Managed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abandoned Plan Review</fullName>
            </value>
            <value>
                <fullName>At Risk Client</fullName>
            </value>
            <value>
                <fullName>Billing Cases</fullName>
            </value>
            <value>
                <fullName>Business Intelligence Cases</fullName>
            </value>
            <value>
                <fullName>Client Feedback</fullName>
            </value>
            <value>
                <fullName>Compliance Cases</fullName>
            </value>
            <value>
                <fullName>Distributions Cases</fullName>
            </value>
            <value>
                <fullName>Force Out Distribution</fullName>
            </value>
            <value>
                <fullName>Implementations Cases</fullName>
            </value>
            <value>
                <fullName>JIRA Submission</fullName>
            </value>
            <value>
                <fullName>Marketing Cases</fullName>
            </value>
            <value>
                <fullName>Operations Cases</fullName>
            </value>
            <value>
                <fullName>Partnership Support</fullName>
            </value>
            <value>
                <fullName>Payroll Inbox</fullName>
            </value>
            <value>
                <fullName>Payroll Koncierge</fullName>
            </value>
            <value>
                <fullName>PRKS</fullName>
            </value>
            <value>
                <fullName>Product Innovation Cases</fullName>
            </value>
            <value>
                <fullName>Reconciliations &amp; Withdrawals</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>SaverSuccess</fullName>
            </value>
            <value>
                <fullName>Servicing</fullName>
            </value>
            <value>
                <fullName>Shared Team Case</fullName>
            </value>
            <value>
                <fullName>Simply TPA</fullName>
            </value>
            <value>
                <fullName>Single(k) Cases</fullName>
            </value>
            <value>
                <fullName>Transitions Cases</fullName>
            </value>
            <value>
                <fullName>Web Form Servicing</fullName>
            </value>
            <value>
                <fullName>ZenOps Cases</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure__c/fields/Global_Default__c.field-meta.xml
<CustomField>
    <fullName>Global_Default__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Global Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure__c/fields/Object_Managed__c.field-meta.xml
<CustomField>
    <fullName>Object_Managed__c</fullName>
    <label>Object Managed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Add-On Product</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Transition</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Breakdown_Structure__c/recordTypes/Case_WBS.recordType-meta.xml
<RecordType>
    <fullName>Case_WBS</fullName>
    <active>true</active>
    <label>Case WBS</label>
</RecordType>

force-app/main/default/classes/CaseSLA_TEST.cls
@isTest
private class CaseSLA_TEST {
  @TestSetup
  static void makeData() {
    Id wbsTypeId = Work_Breakdown_Structure__c.SobjectType.getDescribe(SObjectDescribeOptions.DEFERRED)
      .getRecordTypeInfosByDeveloperName()
      .get('Case_WBS')
      .getRecordTypeId();
    Id pdTypeId = Project_Deliverables__c.SobjectType.getDescribe(SObjectDescribeOptions.DEFERRED)
      .getRecordTypeInfosByDeveloperName()
      .get('Case_Deliverable')
      .getRecordTypeId();
    Work_Breakdown_Structure__c wbs = new Work_Breakdown_Structure__c(
      Name = 'Global Default',
      Global_Default__c = true,
      Object_Managed__c = 'Case',
      RecordTypeId = wbsTypeId
    );
    insert wbs;
    Project_Deliverables__c pd = new Project_Deliverables__c(
      Name = 'Default',
      Default__c = true,
      First_Response_Time_Hours__c = 8,
      Case_Close_Time_Hours__c = 16,
      RecordTypeId = pdTypeId,
      Work_Breakdown_Structure__c = wbs.Id,
      Active__c = true
    );
    insert pd;
    wbs.Active__c = true;
    update wbs;
    Work_Breakdown_Structure__c wbs2 = new Work_Breakdown_Structure__c(
      Name = 'Compliance',
      Object_Managed__c = 'Case',
      RecordTypeId = wbsTypeId,
      Case_Record_Type__c = 'Compliance Cases'
    );
    insert wbs2;
    Project_Deliverables__c pd2 = new Project_Deliverables__c(
      Name = 'New Comp',
      Category__c = 'New Comp',
      RecordTypeId = pdTypeId,
      Work_Breakdown_Structure__c = wbs2.Id,
      Case_Close_Time_Hours__c = 16,
      Active__c = true
    );
    insert pd2;
    Project_Deliverables__c pd3 = new Project_Deliverables__c(
      Name = 'Default',
      Default__c = true,
      RecordTypeId = pdTypeId,
      Work_Breakdown_Structure__c = wbs2.Id,
      First_Response_Time_Hours__c = 8,
      Active__c = true
    );
    insert pd3;
    wbs2.Active__c = true;
    update wbs2;
  }

  @isTest
  static void testGlobalDefault() {
    Id caseServTypeId = Case.SobjectType.getDescribe(SObjectDescribeOptions.DEFERRED).getRecordTypeInfosByDeveloperName().get('Servicing').getRecordTypeId();
    Case c = new Case(Subject = 'testCase', RecordTypeId = caseServTypeId);
    Test.startTest();
    insert c;
    Test.stopTest();
    c = [SELECT Id, Goal_FR_DT_Stamp__c, Goal_Close_DT_Stamp__c, Expected_Days_to_Close__c, Project_Deliverable__c FROM Case WHERE Id = :c.Id];
    Assert.isNotNull(c.Goal_FR_DT_Stamp__c, 'Goal FR DT Stamp should not be null');
    Assert.isNotNull(c.Goal_Close_DT_Stamp__c, 'Goal Close DT Stamp should not be null');
    Assert.isNotNull(c.Expected_Days_to_Close__c, 'Expected Days to Close should not be null');
    Assert.areEqual(
      c.Project_Deliverable__c,
      [SELECT Id FROM Project_Deliverables__c WHERE Default__c = TRUE AND Work_Breakdown_Structure__r.Global_Default__c = TRUE LIMIT 1].Id,
      'Project Deliverable should be the default under global default wbs'
    );
  }

  @isTest
  static void testRecordTypeDefault() {
    Id caseCompTypeId = Case.SobjectType.getDescribe(SObjectDescribeOptions.DEFERRED).getRecordTypeInfosByDeveloperName().get('Compliance').getRecordTypeId();
    Case c = new Case(Subject = 'testCase', RecordTypeId = caseCompTypeId);
    Test.startTest();
    insert c;
    Test.stopTest();
    c = [SELECT Id, Goal_FR_DT_Stamp__c, Goal_Close_DT_Stamp__c, Expected_Days_to_Close__c, Project_Deliverable__c FROM Case WHERE Id = :c.Id];
    Assert.isNotNull(c.Goal_FR_DT_Stamp__c, 'Goal FR DT Stamp should not be null');
    Assert.isNull(c.Goal_Close_DT_Stamp__c, 'Goal Close DT Stamp should be null');
    Assert.isNull(c.Expected_Days_to_Close__c, 'Expected Days to Close should be null');
    Assert.areEqual(
      c.Project_Deliverable__c,
      [SELECT Id FROM Project_Deliverables__c WHERE Default__c = TRUE AND Work_Breakdown_Structure__r.Case_Record_Type__c = 'Compliance Cases' LIMIT 1].Id,
      'Project Deliverable should be the default under compliance wbs'
    );
  }

  @isTest
  static void testCategorySpecific() {
    Id caseCompTypeId = Case.SobjectType.getDescribe(SObjectDescribeOptions.DEFERRED).getRecordTypeInfosByDeveloperName().get('Compliance').getRecordTypeId();
    Case c = new Case(Subject = 'testCase', RecordTypeId = caseCompTypeId, Category__c = 'New Comp');
    Test.startTest();
    insert c;
    Test.stopTest();
    c = [SELECT Id, Goal_FR_DT_Stamp__c, Goal_Close_DT_Stamp__c, Expected_Days_to_Close__c, Project_Deliverable__c FROM Case WHERE Id = :c.Id];
    Assert.isNull(c.Goal_FR_DT_Stamp__c, 'Goal FR DT Stamp should be null');
    Assert.isNotNull(c.Goal_Close_DT_Stamp__c, 'Goal Close DT Stamp should not be null');
    Assert.isNotNull(c.Expected_Days_to_Close__c, 'Expected Days to Close should not be null');
    Assert.areEqual(
      c.Project_Deliverable__c,
      [SELECT Id FROM Project_Deliverables__c WHERE Category__c = 'New Comp' AND Work_Breakdown_Structure__r.Case_Record_Type__c = 'Compliance Cases' LIMIT 1]
      .Id,
      'Project Deliverable should be new comp under compliance wbs'
    );
  }
}