force-app/main/default/objects/Case/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Plan this case is associated with.   Select &quot;Multiple Plans/Unidentified Plan&quot; if the case is regarding more than one plan or a not a specific plan.</description>
    <inlineHelpText>Plan this case is associated with.   Select &quot;Multiple Plans/Unidentified Plan&quot; if the case is regarding more than one plan or a not a specific plan.</inlineHelpText>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Health_Score__c/Client_Health_Score__c.object-meta.xml
<CustomObject>
    <description>Object to track changes in client health score</description>
    <label>Client Health Score</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Client Health Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Health Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Health_Score__c/fields/Client_Health_Score__c.field-meta.xml
<CustomField>
    <fullName>Client_Health_Score__c</fullName>
    <description>Client Health Score stamped when it changes on a Plan</description>
    <inlineHelpText>Client Health Score stamped when it changes on a Plan</inlineHelpText>
    <label>Client Health Score</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Health_Score__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <description>Plan the client health score is for</description>
    <inlineHelpText>Plan the client health score is for</inlineHelpText>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Client Health Scores</relationshipLabel>
    <relationshipName>Client_Health_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/HM_Child__mdt.object-meta.xml
<CustomObject>
    <label>HM_Child</label>
    <pluralLabel>HM_Children</pluralLabel>
</CustomObject>

force-app/main/default/objects/HM_Child__mdt/fields/Filter_Field2__c.field-meta.xml
<CustomField>
    <fullName>Filter_Field2__c</fullName>
    <label>Filter Field2</label>
    <metadataRelationshipControllingField>HM_Child__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>HM_Children1</relationshipLabel>
    <relationshipName>HM_Children1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Filter_Field3__c.field-meta.xml
<CustomField>
    <fullName>Filter_Field3__c</fullName>
    <label>Filter Field3</label>
    <metadataRelationshipControllingField>HM_Child__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>HM_Children2</relationshipLabel>
    <relationshipName>HM_Children2</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Filter_Field__c.field-meta.xml
<CustomField>
    <fullName>Filter_Field__c</fullName>
    <label>Filter Field</label>
    <metadataRelationshipControllingField>HM_Child__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>HM_Children</relationshipLabel>
    <relationshipName>HM_Children</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Filter_Field_Value2__c.field-meta.xml
<CustomField>
    <fullName>Filter_Field_Value2__c</fullName>
    <label>Filter Field Value2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Filter_Field_Value3__c.field-meta.xml
<CustomField>
    <fullName>Filter_Field_Value3__c</fullName>
    <label>Filter Field Value3</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Filter_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Filter_Field_Value__c</fullName>
    <label>Filter Field Value</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Max_Age__c.field-meta.xml
<CustomField>
    <fullName>Max_Age__c</fullName>
    <label>Max Age (Days)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>HM_Children</relationshipLabel>
    <relationshipName>HM_Children</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Score_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Score_Threshold__c</fullName>
    <label>Score Threshold</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HM_Setting__mdt/HM_Setting__mdt.object-meta.xml
<CustomObject>
    <label>HM_Setting</label>
    <pluralLabel>HM_Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/HM_Setting__mdt/fields/Age_of_Reduction__c.field-meta.xml
<CustomField>
    <fullName>Age_of_Reduction__c</fullName>
    <description>Age in days after which score begins ticking towards 0</description>
    <inlineHelpText>Age in days after which score begins ticking towards 0</inlineHelpText>
    <label>Age of Reduction</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HM_Setting__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Client_Health_Settings</relationshipLabel>
    <relationshipName>Client_Health_Settings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/HM_Setting__mdt/fields/Reduction_per_Day__c.field-meta.xml
<CustomField>
    <fullName>Reduction_per_Day__c</fullName>
    <description>Score is reduced by this percentage for every day the age of reduction threshold is exceeded until it reaches 0</description>
    <inlineHelpText>Score is reduced by this percentage for every day the age of reduction threshold is exceeded until it reaches 0</inlineHelpText>
    <label>Reduction per Day</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/HM_Setting__mdt/fields/Related_Date_Field__c.field-meta.xml
<CustomField>
    <fullName>Related_Date_Field__c</fullName>
    <description>Field used for aging score</description>
    <inlineHelpText>Field used for aging score</inlineHelpText>
    <label>Related Date Field</label>
    <metadataRelationshipControllingField>HM_Setting__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>HM_Settings2</relationshipLabel>
    <relationshipName>HM_Settings2</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/HM_Setting__mdt/fields/Round_Up_Weight__c.field-meta.xml
<CustomField>
    <fullName>Round_Up_Weight__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When calculating a subtotal, if one score input has this checked, the total weight will be bumped to 100%.

For example, if a CSAT subtotal field has only the input of Sponsor CSAT weighted at 80%, the score will be calculated as if the weight is 100%</description>
    <inlineHelpText>When calculating a subtotal, if one score input has this checked, the total weight will be bumped to 100%.</inlineHelpText>
    <label>Round Up Weight</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HM_Setting__mdt/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>Score value between -1.00 and 1.00</description>
    <inlineHelpText>Score value between -1.00 and 1.00</inlineHelpText>
    <label>Score</label>
    <precision>3</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HM_Setting__mdt/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field</label>
    <metadataRelationshipControllingField>HM_Setting__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>HM_Settings</relationshipLabel>
    <relationshipName>HM_Settings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/HM_Setting__mdt/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <label>Target Field</label>
    <metadataRelationshipControllingField>HM_Setting__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>HM_Settings1</relationshipLabel>
    <relationshipName>HM_Settings1</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/HM_Setting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Comma separated values that, if present in the source field, will apply this score.  Use &quot;!other&quot; to act as a catch all for any values specified.</description>
    <inlineHelpText>Comma separated values that, if present in the source field, will apply this score.  Use &quot;!other&quot; to act as a catch all for any values specified.</inlineHelpText>
    <label>Value</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HM_Setting__mdt/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>Percent weight of score applied to subtotal field.  If score is 1 with a weight of 20%, subtotal field will show 0.20</description>
    <inlineHelpText>Percent weight of score applied to subtotal field.</inlineHelpText>
    <label>Weight</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/HM_Subtotal__mdt/HM_Subtotal__mdt.object-meta.xml
<CustomObject>
    <label>HM_Subtotal</label>
    <pluralLabel>HM_Subtotals</pluralLabel>
</CustomObject>

force-app/main/default/objects/HM_Subtotal__mdt/fields/Negative_Message__c.field-meta.xml
<CustomField>
    <fullName>Negative_Message__c</fullName>
    <description>Message to display in health info if score is less than 0</description>
    <inlineHelpText>Message to display in health info if score is less than 0</inlineHelpText>
    <label>Negative Message</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HM_Subtotal__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>HM_Subtotals</relationshipLabel>
    <relationshipName>HM_Subtotals</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/HM_Subtotal__mdt/fields/Positive_Message__c.field-meta.xml
<CustomField>
    <fullName>Positive_Message__c</fullName>
    <description>Message to display in health info if score is greater than 0</description>
    <inlineHelpText>Message to display in health info if score is greater than 0</inlineHelpText>
    <label>Positive Message</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HM_Subtotal__mdt/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field</label>
    <metadataRelationshipControllingField>HM_Subtotal__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>HM_Subtotals1</relationshipLabel>
    <relationshipName>HM_Subtotals1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/HM_Subtotal__mdt/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>Percent weight of total score</description>
    <inlineHelpText>Percent weight of total score</inlineHelpText>
    <label>Weight</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <description>Created once Implementation is completed.</description>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Client_Health_Information__c.field-meta.xml
<CustomField>
    <fullName>Client_Health_Information__c</fullName>
    <description>Automated process indicates positive and negative metrics that are affecting the clients health.</description>
    <inlineHelpText>Automated process indicates positive and negative metrics that are affecting the clients health.</inlineHelpText>
    <label>Client Health Information</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/HM_ScoreCalc.cls
public without sharing class HM_ScoreCalc {
  public static Map<String, HM_Setting__mdt> fieldVal = new Map<String, HM_Setting__mdt>();
  public static Map<String, String> targetFieldMap = new Map<String, String>();
  public static Map<String, String> sourceFieldMap = new Map<String, String>();
  public static List<HM_ChildMod> childList = new List<HM_ChildMod>();
  public static String scoreMessages = '';

  public static void calcScores(Map<Id, Plan__c> planMap) {
    Set<Id> planIdsOther = planMap.keySet();

    Map<String, String> filterFieldMap = new Map<String, String>();
    Set<String> fieldDurableIds = new Set<String>();
    Set<String> targetDurableIds = new Set<String>();
    Set<String> sourceDurableIds = new Set<String>();

    //Retrieve HM_Setting metadata records
    for (HM_Setting__mdt hm : HM_Setting__mdt.getAll().values()) {
      List<String> values = hm.Value__c.split(',');
      for (String value : values) {
        //This is used to match settings records with plan fields + values.  Key is "durableId,value"
        String key = hm.Source_Field__c + ',' + value;
        fieldVal.put(key, hm);
      }
      targetDurableIds.add(hm.Related_Date_Field__c);
      targetDurableIds.add(hm.Target_Field__c);
      sourceDurableIds.add(hm.Source_Field__c);
    }

    //Assign field definition IDs and query them to get the QualifiedApiName
    fieldDurableIds.addAll(targetDurableIds);
    fieldDurableIds.addAll(sourceDurableIds);

    //Pull child relationship metadata records, then store field Ids for query
    Set<String> childObjectDurableIds = new Set<String>();
    Set<String> childFieldDurableIds = new Set<String>();
    List<HM_Child__mdt> hmChildMdt = HM_Child__mdt.getAll().values();
    for (HM_Child__mdt hc : hmChildMdt) {
      childObjectDurableIds.add(hc.Object__c);
      childFieldDurableIds.add(hc.Filter_Field__c);
      childFieldDurableIds.add(hc.Filter_Field2__c);
      childFieldDurableIds.add(hc.Filter_Field3__c);
    }
    fieldDurableIds.addAll(childFieldDurableIds);

    //Set up maps for source and target fields
    //DurableID is the key, and the value is the QualifiedApiName of the field
    for (FieldDefinition field : [
      SELECT Id, QualifiedApiName, DurableId
      FROM FieldDefinition
      WHERE DurableId IN :fieldDurableIds
      WITH SECURITY_ENFORCED
    ]) {
      if (sourceDurableIds.contains(field.DurableId)) {
        sourceFieldMap.put(field.DurableId, field.QualifiedApiName);
      } else if (targetDurableIds.contains(field.DurableId)) {
        targetFieldMap.put(field.DurableId, field.QualifiedApiName);
      } else if (childFieldDurableIds.contains(field.DurableId)) {
        filterFieldMap.put(field.DurableId, field.QualifiedApiName);
      }
    }
    Map<String, String> childIdApiMap = new Map<String, String>();
    for (EntityDefinition ed : [
      SELECT DurableId, QualifiedApiName
      FROM EntityDefinition
      WHERE DurableId IN :childObjectDurableIds
      WITH SECURITY_ENFORCED
    ]) {
      childIdApiMap.put(ed.DurableId, ed.QualifiedApiName);
    }
    for (HM_Child__mdt hc : hmChildMdt) {
      HM_ChildMod c = new HM_ChildMod();
      c.objectName = childIdApiMap.get(hc.Object__c);
      c.maxAge = hc.Max_Age__c;
      c.threshold = hc.Score_Threshold__c;
      c.score = hc.Score__c;
      c.message = hc.Message__c;
      c.filterField = filterFieldMap.get(hc.Filter_Field__c);
      c.filterField2 = filterFieldMap.get(hc.Filter_Field2__c);
      c.filterField3 = filterFieldMap.get(hc.Filter_Field3__c);
      c.filterFieldValue = hc.Filter_Field_Value__c;
      c.filterFieldValue2 = hc.Filter_Field_Value2__c;
      c.filterFieldValue3 = hc.Filter_Field_Value3__c;
      childList.add(c);
    }
    String childQuery = HM_Helpers.buildChildQuery(childList);

    //Define fields to be retrieved from plan
    List<Plan__c> plans = database.query(
      'SELECT Id' +
        String.escapeSingleQuotes(childQuery) +
        ' FROM Plan__c WHERE Id IN :planIdsOther'
    );

    Map<String, List<SObject>> planChildMap = new Map<String, List<SObject>>();

    Set<String> relNames = new Set<String>();
    for (HM_ChildMod hcm : childList) {
      relNames.add(hcm.relName);
    }

    for (Plan__c p : plans) {
      for (String relName : relNames) {
        List<SObject> l = p.getSObjects(relName);
        if (l != null) {
          String planRelKey = p.Id + ',' + relName;
          planChildMap.put(planRelKey, l);
        }
      }
    }
    assignPlanScores(planMap, planChildMap);
  }

  //Checks the plan for field/fieldvalue pairs by comparing each to the fieldVal map
  //A new HM_Score is created for each match
  private static Map<Id, Plan__c> assignPlanScores(
    Map<Id, Plan__c> planMap,
    Map<String, List<SObject>> planRelMap
  ) {
    List<HM_Subtotal__mdt> hmSubtotals = HM_Subtotal__mdt.getAll().values();
    for (String planKey : planMap.keySet()) {
      Plan__c plan = planMap.get(planKey);
      scoreMessages = '';
      List<HM_Score> scores = new List<HM_Score>();

      for (String key : sourceFieldMap.keySet()) {
        String item = sourceFieldMap.get(key);
        //key is durableId of the plan field + , + value of the plan field
        String searchKey = key + ',' + plan.get(item);
        searchKey = searchKey.removeEnd('.0');
        String searchKeyAlt = key + ',!other';
        HM_Setting__mdt hm = new HM_Setting__mdt();
        //Tries to match this field's value with a setting record
        if (fieldVal.containsKey(searchKey)) {
          hm = fieldVal.get(searchKey);
        } else if (fieldVal.containsKey(searchKeyAlt)) {
          hm = fieldVal.get(searchKeyAlt);
        }

        if (hm.Score__c != null) {
          HM_Score s = new HM_Score();
          s.weight = hm.Weight__c;
          s.totalWeight = 0;
          s.subtotalField = targetFieldMap.get(hm.Target_Field__c);
          s.ageDateField = targetFieldMap.get(hm.Related_Date_Field__c);
          s.reductionAge = hm.Age_of_Reduction__c;
          s.reductionStep = hm.Reduction_per_Day__c;
          s.weight100 = hm.Round_Up_Weight__c;
          s.score = (s.ageDateField != null)
            ? HM_Helpers.scoreAgeReduction(plan, s, hm.Score__c)
            : hm.Score__c;
          if (s.score != null) {
            scores.add(s);
          }
        }
      }
      if (!scores.isEmpty() || !hmSubtotals.isEmpty()) {
        wipeSubtotals(plan, hmSubtotals);
        assignSubtotals(plan, scores);
      }
      if (!hmSubtotals.isEmpty()) {
        assignTotal(plan, hmSubtotals, planRelMap);
      }
      plan.Client_Health_Information__c = scoreMessages;
    }
    return planMap;
  }

  //List of HM_Score records are added up to be applied to the plan's subtotal fields
  //Magnitude of each HM_Score will be reduced by age, if applicable
  //Multiple HM_Scores could contribute to one subtotal field, so weighting is applied and added to the totalweight for each subtotalfield
  //Total weight is normalized to equal 100%, so it could be greater or less than the sum of its parts.
  private static Plan__c assignSubtotals(Plan__c plan, List<HM_Score> scores) {
    Map<String, HM_Score> scoreMap = new Map<String, HM_Score>();
    for (HM_Score s : scores) {
      Decimal tempScore = 0;
      Decimal tempTotalWeight = 0;
      if (scoreMap.containsKey(s.subtotalField)) {
        tempScore = scoreMap.get(s.subtotalField).score;
        tempTotalWeight = scoreMap.get(s.subtotalField).totalWeight;
        s.weight100 = (scoreMap.get(s.subtotalField).weight100)
          ? true
          : s.weight100;
      }
      tempScore += (s.score * (s.weight / 100));
      tempTotalWeight += s.weight;
      s.score = tempScore;
      s.totalWeight += tempTotalWeight;
      scoreMap.put(s.subtotalField, s);
    }

    for (String key : scoreMap.keyset()) {
      HM_Score item = scoreMap.get(key);
      item.score = (item.weight100)
        ? (item.score / (item.totalWeight / 100))
        : item.score;
      plan.put(key, item.score);
    }
    return plan;
  }

  //Checks the plan's fields that have been assigned by the subtotals step, totaling them up with the corresponding weights from the subtotal mdt
  //After weighted subtotal fields are added, total has child modifiers added to it.
  //Score is normalized to fit between 0 -> 100
  private static Plan__c assignTotal(
    Plan__c plan,
    List<HM_Subtotal__mdt> subtotals,
    Map<String, List<SObject>> planRelMap
  ) {
    Decimal totalScore = 0;
    Decimal totalWeight = 0;
    for (HM_Subtotal__mdt subtotalInfo : subtotals) {
      String sourceField = targetFieldMap.get(subtotalInfo.Source_Field__c);
      Decimal subScore = Decimal.valueOf(plan.get(sourceField).toString());
      subScore *= (subtotalInfo.Weight__c);
      if (subScore > 0) {
        addScoreMessage(subScore, subTotalInfo.Positive_Message__c);
      } else if (subScore < 0) {
        addScoreMessage(subScore, subTotalInfo.Negative_Message__c);
      }
      totalScore += subScore;
      totalWeight += subtotalInfo.Weight__c;
    }
    totalScore += addChildMods(plan, planRelMap);
    if (totalScore < 0) {
      totalScore = 0;
    } else if (totalScore > 100) {
      totalScore = 100;
    }
    plan.Client_Health_Score__c = totalScore;
    return plan;
  }

  //Loops through child relationships of plan defined by HM_ChildMods, counting up each one that meets the HM_ChildMod's criteria
  //If enough meet the criteria to reach the threshold, a modifier is added to the score and a message is added
  private static Decimal addChildMods(
    Plan__c plan,
    Map<String, List<SObject>> planRelMap
  ) {
    Decimal mod = 0;
    for (HM_ChildMod hmChild : childList) {
      Integer count = 0;
      List<SObject> relatedList = planRelMap.get(
        plan.Id + ',' + hmChild.relName
      );
      if (relatedList == null) {
        continue;
      }
      for (SObject child : relatedList) {
        count += HM_Helpers.checkChildRecord(child, hmChild);
      }
      if (count >= hmChild.threshold) {
        mod += hmChild.score;
        addScoreMessage(hmChild.score, hmChild.message);
      }
    }
    return mod;
  }

  private static void addScoreMessage(Decimal score, String message) {
    if (message == null) {
      return;
    }
    final String formattedMessage = HM_Helpers.getScoreMessage(score, message);
    scoreMessages += (scoreMessages == '')
      ? formattedMessage
      : '\r\n' + formattedMessage;
  }

  //Resets all subtotal fields to 0 before calc.  Used in case there aren't any valid scores for a field yet
  private static Plan__c wipeSubtotals(
    Plan__c plan,
    List<HM_Subtotal__mdt> hmSubtotals
  ) {
    for (HM_Subtotal__mdt subtotal : hmSubtotals) {
      plan.put(targetFieldMap.get(subtotal.Source_Field__c), 0);
    }
    return plan;
  }

  public class HM_Score {
    public Decimal score;
    public Decimal weight;
    public Decimal totalWeight;
    public String subtotalField;
    public Decimal reductionAge;
    public Decimal reductionStep;
    public String ageDateField;
    public Boolean weight100;
  }

  public class HM_ChildMod {
    public String objectName;
    public String relName;
    public Decimal maxAge;
    public Decimal score;
    public Decimal threshold;
    public String message;
    public String filterField;
    public String filterFieldValue;
    public String filterField2;
    public String filterFieldValue2;
    public String filterField3;
    public String filterFieldValue3;
  }
}