force-app/main/default/objects/Case/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Plan this case is associated with.   Select &quot;Multiple Plans/Unidentified Plan&quot; if the case is regarding more than one plan or a not a specific plan.</description>
    <inlineHelpText>Plan this case is associated with.   Select &quot;Multiple Plans/Unidentified Plan&quot; if the case is regarding more than one plan or a not a specific plan.</inlineHelpText>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Health_Score__c/Client_Health_Score__c.object-meta.xml
<CustomObject>
    <description>Object to track changes in client health score</description>
    <label>Client Health Score</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Client Health Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Health Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Health_Score__c/fields/Client_Health_Score__c.field-meta.xml
<CustomField>
    <fullName>Client_Health_Score__c</fullName>
    <description>Client Health Score stamped when it changes on a Plan</description>
    <inlineHelpText>Client Health Score stamped when it changes on a Plan</inlineHelpText>
    <label>Client Health Score</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Health_Score__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <description>Plan the client health score is for</description>
    <inlineHelpText>Plan the client health score is for</inlineHelpText>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Client Health Scores</relationshipLabel>
    <relationshipName>Client_Health_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Escalation__c/Escalation__c.object-meta.xml
<CustomObject>
    <label>Escalation</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Escalation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Escalations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Escalation__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Escalations</relationshipLabel>
    <relationshipName>Escalations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Escalation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>De-Escalated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/HM_Child__mdt.object-meta.xml
<CustomObject>
    <label>HM_Child</label>
    <pluralLabel>HM_Children</pluralLabel>
</CustomObject>

force-app/main/default/objects/HM_Child__mdt/fields/Filter_Field2__c.field-meta.xml
<CustomField>
    <fullName>Filter_Field2__c</fullName>
    <label>Filter Field2</label>
    <metadataRelationshipControllingField>HM_Child__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>HM_Children1</relationshipLabel>
    <relationshipName>HM_Children1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Filter_Field3__c.field-meta.xml
<CustomField>
    <fullName>Filter_Field3__c</fullName>
    <label>Filter Field3</label>
    <metadataRelationshipControllingField>HM_Child__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>HM_Children2</relationshipLabel>
    <relationshipName>HM_Children2</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Filter_Field__c.field-meta.xml
<CustomField>
    <fullName>Filter_Field__c</fullName>
    <label>Filter Field</label>
    <metadataRelationshipControllingField>HM_Child__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>HM_Children</relationshipLabel>
    <relationshipName>HM_Children</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Filter_Field_Value2__c.field-meta.xml
<CustomField>
    <fullName>Filter_Field_Value2__c</fullName>
    <label>Filter Field Value2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Filter_Field_Value3__c.field-meta.xml
<CustomField>
    <fullName>Filter_Field_Value3__c</fullName>
    <label>Filter Field Value3</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Filter_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Filter_Field_Value__c</fullName>
    <label>Filter Field Value</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Max_Age__c.field-meta.xml
<CustomField>
    <fullName>Max_Age__c</fullName>
    <label>Max Age (Days)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>HM_Children</relationshipLabel>
    <relationshipName>HM_Children</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HM_Child__mdt/fields/Score_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Score_Threshold__c</fullName>
    <label>Score Threshold</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <description>Created once Implementation is completed.</description>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Billing_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Status__c</fullName>
    <description>Indicates status of invoices.</description>
    <inlineHelpText>Indicates status of invoices.</inlineHelpText>
    <label>Billing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Behind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Client_Health_Score__c.field-meta.xml
<CustomField>
    <fullName>Client_Health_Score__c</fullName>
    <description>Client Health Score Calculated by Process Builder</description>
    <inlineHelpText>Client Health Score Calculated by Process Builder</inlineHelpText>
    <label>Client Health Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Date_Most_Recent_Sponsor_Trustee_CSAT__c.field-meta.xml
<CustomField>
    <fullName>Date_Most_Recent_Sponsor_Trustee_CSAT__c</fullName>
    <description>Date of the Most Recent Sponsor/Trustee CSAT</description>
    <inlineHelpText>Date of the Most Recent Sponsor/Trustee CSAT</inlineHelpText>
    <label>Date Most Recent Sponsor/Trustee CSAT</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Most_Recent_CSAT_Score_Sponsor_Trustee__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_CSAT_Score_Sponsor_Trustee__c</fullName>
    <description>1-5 CSAT score from most recent Resolution CSAT Survey from a Sponsor Trustee or Partner</description>
    <inlineHelpText>1-5 CSAT score from most recent Resolution CSAT Survey from a Sponsor Trustee or Partner</inlineHelpText>
    <label>Most Recent CSAT Score (Sponsor/Trustee)</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Payroll_Submission_Status__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Submission_Status__c</fullName>
    <description>Used to track if client is actively submitting their payroll.</description>
    <inlineHelpText>Used to track if client is actively submitting their payroll.</inlineHelpText>
    <label>Payroll Submission Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Behind</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>Never Submitted</fullName>
            </value>
            <value>
                <fullName>Not Contributing</fullName>
            </value>
            <value>
                <fullName>Passive</fullName>
            </value>
            <value>
                <fullName>Plan Termination/Deconversion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Is the plan active or inactive (Deconverted or Terminated)</description>
    <inlineHelpText>Is the plan active or inactive (Deconverted or Terminated)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Transition Pending</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending Abandonment</fullName>
            </value>
            <value>
                <fullName>Status Under Investigation</fullName>
            </value>
            <value>
                <fullName>Frozen Plan</fullName>
            </value>
            <value>
                <fullName>Implementation in Progress</fullName>
            </value>
            <value>
                <fullName>Passive</fullName>
            </value>
            <value>
                <fullName>Implementation Stalled</fullName>
            </value>
            <value>
                <fullName>Active Not Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HM_Tests.cls
@isTest
private class HM_Tests {
  @TestSetup
  static void makeData() {
    // HM_Child__mdt testChild = new HM_Child__mdt(
    //   Label = 'Ten Test Cases',
    //   DeveloperName = 'Ten_Test_Cases',
    //   Max_Age__c = 30,
    //   Score_Threshold__c = 10,
    //   Score__c = -10000,
    //   Message__c = 'Too many cases my dude',
    //   Object__c = 'Case',
    //   Filter_Field__c = 'Case.SuppliedName',
    //   Filter_Field_Value__c = 'BurgerTime',
    //   Filter_Field2__c = 'Case.SuppliedEmail',
    //   Filter_Field_Value2__c = 'testEmail@ubi.webzone',
    //   Filter_Field3__c = 'Case.SuppliedPhone',
    //   Filter_Field_Value3__c = '1111111111'
    // );
    // insert testChild;

    Plan__c p = new Plan__c(
      Name = 'Test Plan HM_Test',
      Status__c = 'Active',
      Date_Most_Recent_Sponsor_Trustee_CSAT__c = Date.today(),
      Most_Recent_CSAT_Score_Sponsor_Trustee__c = 5,
      Billing_Status__c = 'Current',
      Payroll_Submission_Status__c = 'Current'
    );
    insert p;

    List<Case> cList = new List<Case>();
    for (Integer i = 0; i < 10; i++) {
      Case c = new Case(
        Subject = 'Test Case ' + i,
        Plan__c = p.Id,
        SuppliedEmail = 'testEmail@ubi.webzone',
        SuppliedName = 'BurgerTime',
        SuppliedPhone = '1111111111'
      );
      cList.add(c);
    }
    insert cList;

    Escalation__c e = new Escalation__c(
      Plan__c = p.Id,
      Status__c = 'Escalated'
    );
    insert e;
  }

  @isTest
  static void didHMcalc() {
    Plan__c pBefore = [
      SELECT Id, Client_Health_Score__c
      FROM Plan__c
      WHERE Name = 'Test Plan HM_Test'
    ];
    Decimal oldScore = pBefore.Client_Health_Score__c;
    pBefore.Billing_Status__c = 'Behind';
    test.startTest();
    update pBefore;
    test.stopTest();

    Plan__c pAfter = [
      SELECT Id, Client_Health_Score__c
      FROM Plan__c
      WHERE Name = 'Test Plan HM_Test'
    ];

    Assert.areNotEqual(
      oldScore,
      pAfter.Client_Health_Score__c,
      'Expected to get a different Client Health Score'
    );
  }
}