force-app/main/default/objects/QA_Design__c/QA_Design__c.object-meta.xml
<CustomObject>
    <label>QA Design</label>
    <nameField>
        <label>QA Design Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QA Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QA_Design_Version__c/QA_Design_Version__c.object-meta.xml
<CustomObject>
    <label>QA Design Version</label>
    <nameField>
        <label>QA Design Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QA Design Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QA_Design_Version__c/fields/QA_Design__c.field-meta.xml
<CustomField>
    <fullName>QA_Design__c</fullName>
    <label>QA Design</label>
    <referenceTo>QA_Design__c</referenceTo>
    <relationshipLabel>QA Design Versions</relationshipLabel>
    <relationshipName>QA_Design_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QA_Question__c/QA_Question__c.object-meta.xml
<CustomObject>
    <label>QA Question</label>
    <nameField>
        <label>QA Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QA Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QA_Question__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>QA_Question_Info__r.Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QA_Question__c/fields/QA_Question_Info__c.field-meta.xml
<CustomField>
    <fullName>QA_Question_Info__c</fullName>
    <label>QA Question Info</label>
    <referenceTo>QA_Question_Info__c</referenceTo>
    <relationshipLabel>QA Questions</relationshipLabel>
    <relationshipName>QA_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/QA_Question__c/fields/Quality_Assurance_QA__c.field-meta.xml
<CustomField>
    <fullName>Quality_Assurance_QA__c</fullName>
    <label>Quality Assurance (QA)</label>
    <referenceTo>Quality_Assurance_QA__c</referenceTo>
    <relationshipLabel>QA Questions</relationshipLabel>
    <relationshipName>QA_Questions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QA_Question_Info__c/QA_Question_Info__c.object-meta.xml
<CustomObject>
    <label>QA Question Info</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>QA Question Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QA Question Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QA_Question_Info__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Controls the order that the questions will appear on the dynamic form</description>
    <inlineHelpText>Controls order of questions on QA form.  Start at &quot;1&quot;, then &quot;2&quot;, &quot;3&quot;. . .</inlineHelpText>
    <label>Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QA_Question_Info__c/fields/Pass_Fail__c.field-meta.xml
<CustomField>
    <fullName>Pass_Fail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Score value should be 0.  Questions generated using this will have their score set to -100 to fail the form.</description>
    <inlineHelpText>Modifier for checkbox questions.  Question won&apos;t grant any points.  Instead, it will set the form&apos;s score to 0 if checked.</inlineHelpText>
    <label>Pass/Fail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QA_Question_Info__c/fields/QA_Design__c.field-meta.xml
<CustomField>
    <fullName>QA_Design__c</fullName>
    <label>QA Design</label>
    <referenceTo>QA_Design_Version__c</referenceTo>
    <relationshipLabel>QA Question Info</relationshipLabel>
    <relationshipName>QA_Question_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QA_Question_Info__c/fields/Question_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Question_Prompt__c</fullName>
    <description>The label of the question &quot;field&quot; as displayed in a component</description>
    <label>Question Prompt</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QA_Question_Info__c/fields/Score_Value__c.field-meta.xml
<CustomField>
    <fullName>Score_Value__c</fullName>
    <description>The value of this question as a part of the form.  Value of individual questions cannot exceed 100 on a design</description>
    <label>Score Value</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Assurance_QA__c/Quality_Assurance_QA__c.object-meta.xml
<CustomObject>
    <description>Used for teams to conduct quality assurance of various processes and individual performance.</description>
    <label>Quality Assurance (QA)</label>
    <nameField>
        <label>QA Record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quality Assurance (QA)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Assurance_QA__c/fields/QA_Design_Version__c.field-meta.xml
<CustomField>
    <fullName>QA_Design_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QA Design</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>QA_Design_Version__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>QA_Design_Version__c.Department__c</field>
            <operation>equals</operation>
            <valueField>$Source.Department_Dyn__c</valueField>
        </filterItems>
        <filterItems>
            <field>QA_Design_Version__c.QA_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.QA_Type_Dyn__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>QA_Design_Version__c</referenceTo>
    <relationshipLabel>Quality Assurance (QA)</relationshipLabel>
    <relationshipName>Quality_Assurance_QA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QaFormController.cls
public with sharing class QaFormController {
	@AuraEnabled
	public static void updateQaQuestions(List<Qa_Question__c> questionRecords) {
		try {
			Database.update(questionRecords, true, accessLevel.USER_MODE);
		} catch (Exception e) {
			System.debug('The following exception has occurred: ' + e.getMessage());
			throw new AuraHandledException('Something went wrong: ' + e.getMessage());
		}
	}

	@AuraEnabled(cacheable=true)
	public static list<Id> getQuestionIds(Id qaRecordId) {
		List<Id> questionIds = new List<Id>();
		for (QA_Question__c q : [
			SELECT Id
			FROM QA_Question__c
			WHERE Quality_Assurance_QA__c = :qaRecordId
			WITH USER_MODE
			ORDER BY Order__c ASC
		]) {
			questionIds.add(q.Id);
		}
		return questionIds;
	}

	@AuraEnabled(cacheable=true)
	public static list<QA_Question_Info__c> getQuestionInfo(Id qaRecordId) {
		Id qaDesignId = [
			SELECT Id, QA_Design_Version__c
			FROM Quality_Assurance_QA__c
			WHERE Id = :qaRecordId
			WITH USER_MODE
			LIMIT 1
		]
		.QA_Design_Version__c;
		List<QA_Question_Info__c> questionInfoRecords = [
			SELECT Id, Question_Prompt__c, Score_Value__c, Pass_Fail__c
			FROM QA_Question_Info__c
			WHERE QA_Design__c = :qaDesignId
			WITH USER_MODE
			ORDER BY Order__c ASC
		];
		return questionInfoRecords;
	}
}