force-app/main/default/objects/X360Learning_configuration__c/X360Learning_configuration__c.object-meta.xml
<CustomObject>
    <description>Configuration for 360Learning application</description>
    <label>360Learning configuration</label>
    <nameField>
        <label>360Learning configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>360Learning configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/X360Learning_configuration__c/fields/Competitor_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Field_Name__c</fullName>
    <description>Name of the competitor field</description>
    <label>Competitor Field Name</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X360Learning_configuration__c/fields/Tenant_Url__c.field-meta.xml
<CustomField>
    <fullName>Tenant_Url__c</fullName>
    <description>Url of 360Learning platform</description>
    <label>Tenant Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/TestLearningConfigurationRepository.cls
@isTest
public class TestLearningConfigurationRepository {
    @isTest
    static void testGetLearningConfiguration() {
        String competitorFieldName = 'Competitor';
        String tenantUrl = 'team.360mooc.com';
        LearningConfigurationRepository.upsertLearningConfiguration(competitorFieldName, tenantUrl);

        X360Learning_configuration__c learningConfiguration = LearningConfigurationRepository.getLearningConfiguration();

        System.assertEquals(competitorFieldName, learningConfiguration.Competitor_Field_Name__c);
        System.assertEquals(tenantUrl, learningConfiguration.Tenant_Url__c);
    }
}