force-app/main/default/objects/Account/fields/Custodian__c.field-meta.xml
<CustomField>
    <fullName>Custodian__c</fullName>
    <label>Custodian</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MG Trust Company, LLC.</fullName>
            </value>
            <value>
                <fullName>Schwab Trust</fullName>
            </value>
            <value>
                <fullName>National Financial Services</fullName>
            </value>
            <value>
                <fullName>TD Ameritrade</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>In-House</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fund_List__c.field-meta.xml
<CustomField>
    <fullName>Fund_List__c</fullName>
    <label>Fund List</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CensiblyYours</fullName>
            </value>
            <value>
                <fullName>Custom List</fullName>
            </value>
            <value>
                <fullName>ESG</fullName>
            </value>
            <value>
                <fullName>Fidelity / Vanguard</fullName>
            </value>
            <value>
                <fullName>Fidelity Extended</fullName>
            </value>
            <value>
                <fullName>Fidelity Index</fullName>
            </value>
            <value>
                <fullName>FPR</fullName>
            </value>
            <value>
                <fullName>FPR ETF</fullName>
            </value>
            <value>
                <fullName>Globalt I-Shares</fullName>
            </value>
            <value>
                <fullName>Intuit Morningstar List</fullName>
            </value>
            <value>
                <fullName>JPM R2 SmartRetirement</fullName>
            </value>
            <value>
                <fullName>JPM R2 Smart Retirement Blend</fullName>
            </value>
            <value>
                <fullName>JPM R3 SmartRetirement</fullName>
            </value>
            <value>
                <fullName>JPM R3 Smart Retirement Blend</fullName>
            </value>
            <value>
                <fullName>JPM R4 SmartRetirement</fullName>
            </value>
            <value>
                <fullName>JPM R4 Smart Retirement Blend</fullName>
            </value>
            <value>
                <fullName>JPM R5 SmartRetirement</fullName>
            </value>
            <value>
                <fullName>JPM R5 Smart Retirement Blend</fullName>
            </value>
            <value>
                <fullName>JPM R6 SmartRetirement</fullName>
            </value>
            <value>
                <fullName>JPM R6 Smart Retirement Blend</fullName>
            </value>
            <value>
                <fullName>Loring Ward Custom Fund List</fullName>
            </value>
            <value>
                <fullName>Loring Ward  Plan B</fullName>
            </value>
            <value>
                <fullName>Matrix DFA Long List</fullName>
            </value>
            <value>
                <fullName>Matrix Reg Rep List Choice 50bps</fullName>
            </value>
            <value>
                <fullName>Matrix Reg Rep List Plus 75bps</fullName>
            </value>
            <value>
                <fullName>Matrix Reg Rep List Select 100bps</fullName>
            </value>
            <value>
                <fullName>Matrix RIA/Direct Fund List</fullName>
            </value>
            <value>
                <fullName>MML</fullName>
            </value>
            <value>
                <fullName>Morningstar 25 bps</fullName>
            </value>
            <value>
                <fullName>Morningstar 50 bps</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Plan_Status__c.field-meta.xml
<CustomField>
    <fullName>Plan_Status__c</fullName>
    <description>Status of Plan(s) connected to Account. Active Status overrides any others.</description>
    <inlineHelpText>Status of Plan(s) connected to Account. Active Status overrides any others.</inlineHelpText>
    <label>Plan Status</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Plan_Value__c.field-meta.xml
<CustomField>
    <fullName>Plan_Value__c</fullName>
    <description>Plan value based on employee count and service option</description>
    <label>Plan Value</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Safe_Harbor__c.field-meta.xml
<CustomField>
    <fullName>Safe_Harbor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This plan has selected the Safe Harbor feature.</description>
    <inlineHelpText>This field should be checked if the plan has opted for Safe Harbor.</inlineHelpText>
    <label>Safe Harbor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Safe_Harbor_Formula__c.field-meta.xml
<CustomField>
    <fullName>Safe_Harbor_Formula__c</fullName>
    <description>Used for Client Marketing purposes in MC.</description>
    <inlineHelpText>Used for Client Marketing purposes in MC.</inlineHelpText>
    <label>Safe Harbor Formula</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Option__c.field-meta.xml
<CustomField>
    <fullName>Service_Option__c</fullName>
    <label>Service Option</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Saver(k)</fullName>
            </value>
            <value>
                <fullName>Express(k)</fullName>
            </value>
            <value>
                <fullName>Custom(k)</fullName>
            </value>
            <value>
                <fullName>Reserve(k)</fullName>
            </value>
            <value>
                <fullName>Single(k)</fullName>
            </value>
            <value>
                <fullName>Single(k) Plus</fullName>
            </value>
            <value>
                <fullName>RK Only</fullName>
            </value>
            <value>
                <fullName>Single IRA</fullName>
            </value>
            <value>
                <fullName>Express IRA</fullName>
            </value>
            <value>
                <fullName>SIMPLE IRA</fullName>
            </value>
            <value>
                <fullName>Custom(k) MML</fullName>
            </value>
            <value>
                <fullName>Simply Retirement Single(k) Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fund_List__c/Fund_List__c.object-meta.xml
<CustomObject>
    <description>Used for custom and or semi-custom fund lists</description>
    <label>Fund List</label>
    <nameField>
        <label>Fund List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund_List__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fund Lists (Account)</relationshipLabel>
    <relationshipName>Custom_Fund_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fund_List__c/fields/Custodian__c.field-meta.xml
<CustomField>
    <fullName>Custodian__c</fullName>
    <label>Custodian</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MG Trust Company, LLC.</fullName>
            </value>
            <value>
                <fullName>Schwab &amp; Co., Inc.</fullName>
            </value>
            <value>
                <fullName>Schwab Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fund_List__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Plan the Fund List is being created for.</description>
    <inlineHelpText>Plan the Fund List is being created for.</inlineHelpText>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Fund Lists</relationshipLabel>
    <relationshipName>Fund_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <description>Created once Implementation is completed.</description>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Plan is associated with.</description>
    <inlineHelpText>Account Plan is associated with.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Annual_Recurring_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Annual_Recurring_Revenue__c</fullName>
    <description>ARR is the yearly revenue from active subscriptions and/or recurring fees.  Monthly revenue field x12.</description>
    <formula>Monthly_Recurring_Revenue_MRR__c *12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>ARR is the yearly revenue from active subscriptions and/or recurring fees.</inlineHelpText>
    <label>Annual Recurring Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Custodian__c.field-meta.xml
<CustomField>
    <fullName>Custodian__c</fullName>
    <label>Custodian</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Custodian</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Fund_List__c.field-meta.xml
<CustomField>
    <fullName>Fund_List__c</fullName>
    <label>Fund List</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fund_List</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Safe_Harbor__c.field-meta.xml
<CustomField>
    <fullName>Safe_Harbor__c</fullName>
    <description>401(k) Safe Harbor Formula</description>
    <inlineHelpText>401(k) Safe Harbor Formula</inlineHelpText>
    <label>Safe Harbor</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Service_Option__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Safe_Harbor</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Service_Option__c.field-meta.xml
<CustomField>
    <fullName>Service_Option__c</fullName>
    <description>Service Option Selected for the Plan</description>
    <inlineHelpText>Service Option Selected for the Plan</inlineHelpText>
    <label>Service Option</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Option</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Is the plan active or inactive (Deconverted or Terminated)</description>
    <inlineHelpText>Is the plan active or inactive (Deconverted or Terminated)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Transition Pending</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending Abandonment</fullName>
            </value>
            <value>
                <fullName>Status Under Investigation</fullName>
            </value>
            <value>
                <fullName>Frozen Plan</fullName>
            </value>
            <value>
                <fullName>Implementation in Progress</fullName>
            </value>
            <value>
                <fullName>Passive</fullName>
            </value>
            <value>
                <fullName>Implementation Stalled</fullName>
            </value>
            <value>
                <fullName>Active Not Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Custodian.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MG Trust Company, LLC.</fullName>
    </customValue>
    <customValue>
        <fullName>Schwab &amp; Co., Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>Schwab Trust</fullName>
    </customValue>
    <customValue>
        <fullName>National Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>TD Ameritrade</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <description>Where are plan assets be custodied?</description>
    <masterLabel>Custodian</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Fund_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Carbon Collective Fund List 1</fullName>
    </customValue>
    <customValue>
        <fullName>Carbon Collective Fund List 2</fullName>
    </customValue>
    <customValue>
        <fullName>CensiblyYours</fullName>
    </customValue>
    <customValue>
        <fullName>COTA St</fullName>
    </customValue>
    <customValue>
        <fullName>Custom List</fullName>
    </customValue>
    <customValue>
        <fullName>Envestnet</fullName>
    </customValue>
    <customValue>
        <fullName>ESG</fullName>
    </customValue>
    <customValue>
        <fullName>Fidelity Extended</fullName>
    </customValue>
    <customValue>
        <fullName>Fidelity Index</fullName>
    </customValue>
    <customValue>
        <fullName>flexPATH</fullName>
    </customValue>
    <customValue>
        <fullName>FPR</fullName>
    </customValue>
    <customValue>
        <fullName>FPR ETF</fullName>
    </customValue>
    <customValue>
        <fullName>Globalt I-Shares</fullName>
    </customValue>
    <customValue>
        <fullName>Intuit Morningstar List</fullName>
    </customValue>
    <customValue>
        <fullName>JPM R2 SmartRetirement</fullName>
    </customValue>
    <customValue>
        <fullName>JPM R2 Smart Retirement Blend</fullName>
    </customValue>
    <customValue>
        <fullName>JPM R3 SmartRetirement</fullName>
    </customValue>
    <customValue>
        <fullName>JPM R3 Smart Retirement Blend</fullName>
    </customValue>
    <customValue>
        <fullName>JPM R4 SmartRetirement</fullName>
    </customValue>
    <customValue>
        <fullName>JPM R4 Smart Retirement Blend</fullName>
    </customValue>
    <customValue>
        <fullName>JPM R5 SmartRetirement</fullName>
    </customValue>
    <customValue>
        <fullName>JPM R5 Smart Retirement Blend</fullName>
    </customValue>
    <customValue>
        <fullName>JPM R6 SmartRetirement</fullName>
    </customValue>
    <customValue>
        <fullName>JPM R6 Smart Retirement Blend</fullName>
    </customValue>
    <customValue>
        <fullName>Loring Ward &amp;#150 - Plan B</fullName>
    </customValue>
    <customValue>
        <fullName>Loring Ward Custom Fund List</fullName>
    </customValue>
    <customValue>
        <fullName>Matrix DFA Long List</fullName>
    </customValue>
    <customValue>
        <fullName>Matrix Reg Rep List Choice 50bps</fullName>
    </customValue>
    <customValue>
        <fullName>Matrix Reg Rep List Plus 75bps</fullName>
    </customValue>
    <customValue>
        <fullName>Matrix Reg Rep List Select 100bps</fullName>
    </customValue>
    <description>What type of Fund List will Plan be using?</description>
    <masterLabel>Fund List</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Safe_Harbor.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>4% Enhanced Match</fullName>
    </customValue>
    <customValue>
        <fullName>5% Enhanced Match</fullName>
    </customValue>
    <customValue>
        <fullName>6% Enhanced Match</fullName>
    </customValue>
    <customValue>
        <fullName>Basic Match (100% of 1st 3%+50% of next 2%)</fullName>
    </customValue>
    <customValue>
        <fullName>3% Non-Elective Contribution (NEC)</fullName>
    </customValue>
    <customValue>
        <fullName>QACA Basic Match (100% up to 1%, 50% up to 6%)</fullName>
    </customValue>
    <customValue>
        <fullName>3.5% QACA Match</fullName>
    </customValue>
    <customValue>
        <fullName>4% QACA Match</fullName>
    </customValue>
    <customValue>
        <fullName>5% QACA Match</fullName>
    </customValue>
    <customValue>
        <fullName>6% QACA Match</fullName>
    </customValue>
    <customValue>
        <fullName>3% QACA non-elective</fullName>
    </customValue>
    <description>401(k) Safe Harbor Formulas</description>
    <masterLabel>Safe Harbor</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Service_Option.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Saver(k)</fullName>
    </customValue>
    <customValue>
        <fullName>Custom(k)</fullName>
    </customValue>
    <customValue>
        <fullName>Reserve(k)</fullName>
    </customValue>
    <customValue>
        <fullName>RK Only</fullName>
    </customValue>
    <customValue>
        <fullName>Simply Retirement</fullName>
    </customValue>
    <customValue>
        <fullName>Simply Retirement TPA</fullName>
    </customValue>
    <customValue>
        <fullName>Single(k)</fullName>
    </customValue>
    <customValue>
        <fullName>Single(k) Plus</fullName>
    </customValue>
    <customValue>
        <fullName>Single IRA</fullName>
    </customValue>
    <customValue>
        <fullName>Express IRA</fullName>
    </customValue>
    <customValue>
        <fullName>Mega Roth Single(k)</fullName>
    </customValue>
    <customValue>
        <fullName>Single(k) to Custom(k)</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy Saver(k)</fullName>
    </customValue>
    <customValue>
        <fullName>Express(k)</fullName>
    </customValue>
    <customValue>
        <fullName>Simply Retirement Bundled</fullName>
    </customValue>
    <customValue>
        <fullName>Simply Retirement Unbundled</fullName>
    </customValue>
    <customValue>
        <fullName>Simply Retirement Single(k) Plus</fullName>
    </customValue>
    <customValue>
        <fullName>Starter</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Builder</fullName>
    </customValue>
    <customValue>
        <fullName>Franchise</fullName>
    </customValue>
    <customValue>
        <fullName>Custom(k) MML</fullName>
    </customValue>
    <customValue>
        <fullName>Single(k) Lite</fullName>
        <isActive>false</isActive>
        <label>Single(k) Lite</label>
    </customValue>
    <masterLabel>Service Option</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PlanTriggerController.cls
public without sharing class PlanTriggerController {
  public static void createdPlanUpdateAccounts(List<Plan__c> plans) {
    Set<Id> accountIds = new Set<Id>();
    for (Plan__c plan : plans) {
      accountIds.add(plan.Account__c);
    }

    List<Account> accounts = [
      SELECT Id, Custodian__c, Fund_List__c, Service_Option__c, Safe_Harbor_Formula__c, Plan_Status__c
      FROM Account
      WHERE Id IN :accountIds
    ];

    for (Account account : accounts) {
      for (Plan__c plan : plans) {
        if (plan.Account__c == account.Id) {
          account.Custodian__c = plan.Custodian__c;
          account.Fund_List__c = plan.Fund_List__c;
          account.Service_Option__c = plan.Service_Option__c;
          account.Safe_Harbor_Formula__c = plan.Safe_Harbor__c;
          account.Plan_Status__c = plan.Status__c;
        }
      }
    }
    try {
      Database.update(accounts);
    } catch (Exception e) {
      Logger.error('Error updating accounts from PlanTriggerController insert', accounts, e);
    }
    Logger.saveLog();
  }

  public static void afterUpdatePlan(Map<Id, Plan__c> plans) {
    List<Account> accountsToUpdate = new List<Account>();

    Set<Id> accountIds = new Set<Id>();
    for (Plan__c plan : plans.values()) {
      if (plan.Account__c != null) {
        accountIds.add(plan.Account__c);
      }
    }

    List<Plan__c> latestPlans = getLatestPlans(accountIds);
    accountsToUpdate.addAll(accsNeedPlanSync(latestPlans));
    if (!accountsToUpdate.isEmpty()) {
      try {
        Database.update(accountsToUpdate);
      } catch (Exception e) {
        Logger.error('Error updating accounts from PlanTriggerController update', accountsToUpdate, e);
      }
    }
    Logger.saveLog();
  }

  private static List<Plan__c> getLatestPlans(Set<Id> accountIds) {
    Map<Id, Plan__c> accPlanMap = new Map<Id, Plan__c>();
    for (Plan__c plan : [
      SELECT
        Id,
        Status__c,
        Custodian__c,
        Fund_List__c,
        Service_Option__c,
        Safe_Harbor__c,
        Annual_Recurring_Revenue__c,
        CreatedDate,
        Account__r.Id,
        Account__r.Custodian__c,
        Account__r.Fund_List__c,
        Account__r.Service_Option__c,
        Account__r.Safe_Harbor_Formula__c,
        Account__r.Plan_Status__c,
        Account__r.Plan_Value__c,
        Account__r.CreatedDate
      FROM Plan__c
      WHERE Account__c IN :accountIds
      ORDER BY CreatedDate DESC
    ]) {
      if (accPlanMap.containsKey(plan.Account__c) && plan.Status__c == 'Active') {
        Plan__c altPlan = accPlanMap.get(plan.Account__c);
        if (altPlan.Status__c != 'Active') {
          accPlanMap.put(plan.Account__c, plan);
        }
      } else if (!accPlanMap.containsKey(plan.Account__c)) {
        accPlanMap.put(plan.Account__c, plan);
      }
    }
    return accPlanMap.values();
  }

  private static List<Account> accsNeedPlanSync(List<Plan__c> plans) {
    List<Account> accounts2Update = new List<Account>();
    for (Plan__c plan : plans) {
      String planValue = getPlanValue(plan.Annual_Recurring_Revenue__c);
      if (
        plan.Account__r.Custodian__c != plan.Custodian__c ||
        plan.Account__r.Fund_List__c != plan.Fund_List__c ||
        plan.Account__r.Service_Option__c != plan.Service_Option__c ||
        plan.Account__r.Safe_Harbor_Formula__c != plan.Safe_Harbor__c ||
        plan.Account__r.Plan_Status__c != plan.Status__c ||
        plan.Account__r.Plan_Value__c != planValue
      ) {
        accounts2Update.add(
          new Account(
            Id = plan.Account__c,
            Custodian__c = plan.Custodian__c,
            Fund_List__c = plan.Fund_List__c,
            Service_Option__c = plan.Service_Option__c,
            Safe_Harbor_Formula__c = plan.Safe_Harbor__c,
            Plan_Status__c = plan.Status__c,
            Plan_Value__c = planValue
          )
        );
      }
    }
    return accounts2Update;
  }

  private static String getPlanValue(Decimal yrRevenue) {
    final Integer minPlat = 10000;
    final Integer minGold = 6000;
    final Integer minSilver = 2000;
    if (yrRevenue >= minPlat) {
      return 'Platinum';
    } else if (yrRevenue >= minGold) {
      return 'Gold';
    } else if (yrRevenue >= minSilver) {
      return 'Silver';
    } else if (yrRevenue > 0) {
      return 'Bronze';
    } else {
      return null;
    }
  }
}