force-app/main/default/objects/Account/fields/Escalated__c.field-meta.xml
<CustomField>
    <fullName>Escalated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Escalated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Escalation__c/Escalation__c.object-meta.xml
<CustomObject>
    <label>Escalation</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Escalation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Escalations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Escalation__c/fields/Escalated_Account__c.field-meta.xml
<CustomField>
    <fullName>Escalated_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Escalated Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Escalations</relationshipLabel>
    <relationshipName>Escalations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Escalation__c/fields/Escalation_Contact__c.field-meta.xml
<CustomField>
    <fullName>Escalation_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Escalation Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Escalations</relationshipLabel>
    <relationshipName>Escalations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Escalation__c/fields/Implementation__c.field-meta.xml
<CustomField>
    <fullName>Implementation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation</label>
    <referenceTo>Implementation__c</referenceTo>
    <relationshipLabel>Escalations</relationshipLabel>
    <relationshipName>Escalations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Escalation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>De-Escalated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Implementation__c/Implementation__c.object-meta.xml
<CustomObject>
    <description>This object is used by the Implementation&apos;s Teams to set up and track new and conversion plans.</description>
    <label>Implementation</label>
    <nameField>
        <label>Implementation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Associated with Implementation</description>
    <inlineHelpText>Account Associated with Implementation</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Implementations</relationshipLabel>
    <relationshipName>Implementations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Opportunity associated with Implementation</description>
    <inlineHelpText>Opportunity associated with Implementation</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Implementations (Opportunity)</relationshipLabel>
    <relationshipName>Implementations1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Escalated__c.field-meta.xml
<CustomField>
    <fullName>Escalated__c</fullName>
    <formula>Account.Escalated__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Escalated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Implementation__c.field-meta.xml
<CustomField>
    <fullName>Implementation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used for automation mapping contacts to implementation.</description>
    <inlineHelpText>Used for automation mapping contacts to implementation.</inlineHelpText>
    <label>Implementation</label>
    <referenceTo>Implementation__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EscalationControllerTest.cls
@isTest
public class EscalationControllerTest {
    
    @isTest
	public static void testEscalation() {
        String oppRecordType = [SELECT id FROM RecordType WHERE SobjectType = 'Opportunity' AND Name = '401(k)'].Id;
        String oppStage = [SELECT ApiName FROM OpportunityStage WHERE SortOrder = 1].ApiName;
        Account acct = new Account(Name='Test');
        acct.Escalated__c = true;
        acct.NumberOfEmployees = 5;
        insert acct;

        Contact cont = new Contact(LastName='TestCont');
        cont.AccountId = acct.Id;
        insert cont;
        
        Opportunity opp = new Opportunity(Name='Test');
        opp.AccountId = acct.Id;
        opp.StageName = oppStage;
        opp.CloseDate = Date.today();
        opp.Description = 'test';
        opp.RecordTypeId = oppRecordType;
        insert opp;
        
        Implementation__c imp = new Implementation__c(Name='Test');
        imp.Account__c = acct.Id;
        imp.Opportunity_Name__c = opp.Id;
        insert imp;
        
        String acctId = acct.Id;
        String recId  = cont.Id;
        String custId = imp.Id;
        
        Account acct2 = new Account(Name='Test');
        acct2.Escalated__c = false;
        insert acct2;

        Contact cont2 = new Contact(LastName='TestCont');
        cont2.AccountId = acct2.Id;
        insert cont2;
        
        Opportunity opp2 = new Opportunity(Name='Test');
        opp2.AccountId = acct.Id;
        opp2.StageName = oppStage;
        opp2.CloseDate = Date.today();
        opp2.Description = 'test';
        opp2.RecordTypeId = oppRecordType;
        insert opp2;
        
        Implementation__c imp2 = new Implementation__c(Name='Test');
        imp2.Account__c = acct2.Id;
        imp2.Opportunity_Name__c = opp2.Id;
        insert imp2;
        
        String acctId2 = acct2.Id;
        String recId2  = cont2.Id;
        String custId2 = imp2.Id;

        Escalation__c newEsc = new Escalation__c();
        newEsc.Escalated_Account__c = acct.Id;
        newEsc.Escalation_Contact__c = cont.Id;
        newEsc.Status__c = 'Escalated';
        insert newEsc;
        
               
        System.assertEquals(EscalationController.isEscalated(acctId), True, 'Account 1 should show as escalated');
        System.assertEquals(EscalationController.isEscalated(recId), True, 'Contact 1 should show as escalated');
        System.assertEquals(EscalationController.isEscalated(custId), True, 'Implementation 1 should show as escalated');
        System.assertEquals(EscalationController.isEscalated(acctId2), False, 'Account 2 shouldn\'t show as escalated');
        System.assertEquals(EscalationController.isEscalated(recId2), False, 'Contact 2 shouldn\'t show as escalated');
        System.AssertEquals(EscalationController.isEscalated(custId2), False, 'Implementation 2 shouldn\'t show as escalated');
        
        List<Escalation__c> result = EscalationController.getEscalatedRecord(acctId);
        List<Escalation__c> result2 = EscalationController.getEscalatedRecord(recId);
        List<Escalation__c> result3 = EscalationController.getEscalatedRecord(custId);
        system.assertEquals(1, result.size(), 'Controller should return 1 escalation record from accountId');
        system.assertEquals(1, result2.size(), 'Controller should return 1 escalation record from contactId');        
        system.assertEquals(1, result3.size(), 'Controller should return 1 escalation record from impId'); 

    }
}