force-app/main/default/objects/External_Response__c/External_Response__c.object-meta.xml
<CustomObject>
    <label>External Response</label>
    <nameField>
        <displayFormat>ER-{0000}</displayFormat>
        <label>External Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/External_Response__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>External Responses</relationshipLabel>
    <relationshipName>External_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Number_of_Employees__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Employees__c</fullName>
    <description>Used for fee calculations</description>
    <formula>Account.NumberOfEmployees</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Used for fee calculations</inlineHelpText>
    <label>Number of Employees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PRP-{0000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Advisor_CRD__c.field-meta.xml
<CustomField>
    <fullName>Advisor_CRD__c</fullName>
    <label>Advisor CRD</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Advisor_NPN__c.field-meta.xml
<CustomField>
    <fullName>Advisor_NPN__c</fullName>
    <label>Advisor NPN</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Client_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Company_Name__c</fullName>
    <label>Client Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Company_EIN__c.field-meta.xml
<CustomField>
    <fullName>Company_EIN__c</fullName>
    <label>Company EIN</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Company_State__c.field-meta.xml
<CustomField>
    <fullName>Company_State__c</fullName>
    <label>Company State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Company_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Zip_Code__c</fullName>
    <formula>LPAD(TEXT(Company_Zip_Postal_Code__c), 5, &apos;0&apos; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Zip Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Company_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Zip_Postal_Code__c</fullName>
    <label>Company Zip/Postal Code</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Contact_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Phone_Number__c</fullName>
    <label>Contact Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/External_Response__c.field-meta.xml
<CustomField>
    <fullName>External_Response__c</fullName>
    <label>External Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Financial_Professional_Role__c.field-meta.xml
<CustomField>
    <fullName>Financial_Professional_Role__c</fullName>
    <description>This field has a corresponding field on Contact that is updated via flow. If you add/remove a value here, do the same for the Contact field.</description>
    <label>Financial Professional Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>IAR</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Firm_Name__c.field-meta.xml
<CustomField>
    <fullName>Firm_Name__c</fullName>
    <label>Firm Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Insurance_Agency_NPN__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Agency_NPN__c</fullName>
    <label>Insurance Agency NPN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Manual_Callout__c.field-meta.xml
<CustomField>
    <fullName>Manual_Callout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual Callout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Number_of_Employees__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Employees__c</fullName>
    <label>Number of Employees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Plan_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Effective_Date__c</fullName>
    <label>Plan Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Principal_Id__c.field-meta.xml
<CustomField>
    <fullName>Principal_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Principal Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Principal_Opportunity_Closed_Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Principal_Opportunity_Closed_Lost_Reason__c</fullName>
    <label>Principal Opportunity Closed Lost Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Case Not Taken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Principal_Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Principal_Opportunity_Id__c</fullName>
    <label>Principal Opportunity Id</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Principal_Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Principal_Opportunity_Stage__c</fullName>
    <label>Principal Opportunity Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Proposal / Price Quote</fullName>
            </value>
            <value>
                <fullName>Presentation</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Committed</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/TPA_EIN__c.field-meta.xml
<CustomField>
    <fullName>TPA_EIN__c</fullName>
    <label>TPA EIN</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/TPA_Firm_Name__c.field-meta.xml
<CustomField>
    <fullName>TPA_Firm_Name__c</fullName>
    <label>TPA Firm Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Simply_Version__c/Simply_Version__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>To swtich between old and new SimplyAPI</description>
    <label>Simply Version</label>
</CustomObject>

force-app/main/default/objects/Simply_Version__c/fields/New_Version__c.field-meta.xml
<CustomField>
    <fullName>New_Version__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Version</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SimplyCalloutBatchTest.cls
@isTest
public with sharing class SimplyCalloutBatchTest {
	@TestSetup
	static void makeData() {

		Simply_Version__c version;
		try{
			version = [SELECT Id, New_Version__c FROM Simply_Version__c LIMIT 1];
			version.New_Version__c = true;
			update version;
		}  catch (QueryException e) {
            version = new Simply_Version__c(New_Version__c = true);
            insert version;
		}
		Account acc = DataFactory.createAccount();
		Opportunity opp = DataFactory.createOpportunity(acc);
		List<Proposal__c> propLst = DataFactory.createProposals(20, opp);
	}


	@isTest
	public static void testProposalTriggerNew() {
		List<Proposal__c> proposalList = [
			SELECT
				Id,
				Client_Company_Name__c,
				Contact_Phone_Number__c,
				Company_State__c,
				Company_EIN__c,
				Company_Zip_Code__c,
				Plan_Effective_Date__c,
				Number_of_Employees__c,
				Advisor_NPN__c,
				Advisor_CRD__c,
				Firm_Name__c,
				TPA_Firm_Name__c,
				TPA_EIN__c,
				Principal_Opportunity_Id__c,
				Principal_Opportunity_Stage__c,
				Principal_Opportunity_Closed_Lost_Reason__c,
				Company_Zip_Postal_Code__c,
				Financial_Professional_Role__c,
				Insurance_Agency_NPN__c,
				Manual_Callout__c,
				Principal_Id__c
			FROM Proposal__c
			WHERE Advisor_CRD__c = '55555'
		];
		System.debug('proposalList: ' + proposalList);
		for (Proposal__c p : proposalList) {
			System.debug('p.Principal_Id__c: ' + p.Principal_Id__c);
			if (String.valueOf(p.Principal_Id__c).startsWith('0')) {
				p.Financial_Professional_Role__c = 'IAR';
				p.Principal_Opportunity_Stage__c = 'Committed';
				p.Manual_Callout__c = true;
			} else if (String.valueOf(p.Principal_Id__c).startsWith('1')) {
				p.External_Response__c = '{"errors":[1],"client":{"errors":[1],';
				p.Financial_Professional_Role__c = 'RR';
				p.Principal_Opportunity_Stage__c = 'Committed';
			} else if (String.valueOf(p.Principal_Id__c).startsWith('3')) {
				p.Financial_Professional_Role__c = 'RR';
				p.Principal_Opportunity_Stage__c = 'Committed';
			}
		}
		update proposalList;

		Test.setMock(HttpCalloutMock.class, new SimplyCalloutMock());
        Test.startTest();
        Database.executeBatch(new SimplyCalloutBatch());
        Test.stopTest();
	}

	@isTest
	public static void testProposalTriggerFailure() {
		Proposal__c testProp = new Proposal__c();

		testProp.Advisor_CRD__c = '12345';
		testProp.Plan_Effective_Date__c = Date.today();
		testProp.Principal_Opportunity_Stage__c = 'Presentation';
		testProp.Financial_Professional_Role__c = 'IAR';
		testProp.Client_Company_Name__c = 'Client Company 13';
		testProp.Firm_Name__c = 'Advisory Firm 00';
		testProp.Principal_Opportunity_Closed_Lost_Reason__c = 'Unknown';
		testProp.Insurance_Agency_NPN__c = 44444;
		testProp.Contact_Phone_Number__c = '(555)099-4455';
		testProp.Number_of_Employees__c = 5;
		testProp.TPA_Firm_Name__c = 'TPA Firm 01';
		testProp.Company_Zip_Postal_Code__c = 12345;
		testProp.Company_State__c = 'California';
		testProp.Advisor_NPN__c = '12345';
		testProp.TPA_EIN__c = '222222222';
		testProp.Company_EIN__c = '111111111';
		testProp.Principal_Id__c = '1234567891';
		insert testProp;

		testProp.Principal_Opportunity_Stage__c = 'Committed';
		testProp.Financial_Professional_Role__c = 'IA';
		update testProp;
		Test.setMock(HttpCalloutMock.class, new SimplyCalloutMockFail());
		Test.startTest();
        Database.executeBatch(new SimplyCalloutBatch());
        Test.stopTest();

	}

	@isTest
	public static void testSchedulerTest() {
		Proposal__c testProp = new Proposal__c();

		testProp.Advisor_CRD__c = '12345';
		testProp.Plan_Effective_Date__c = Date.today();
		testProp.Principal_Opportunity_Stage__c = 'Presentation';
		testProp.Financial_Professional_Role__c = 'IAR';
		testProp.Client_Company_Name__c = 'Client Company 13';
		testProp.Firm_Name__c = 'Advisory Firm 00';
		testProp.Principal_Opportunity_Closed_Lost_Reason__c = 'Unknown';
		testProp.Insurance_Agency_NPN__c = 44444;
		testProp.Contact_Phone_Number__c = '(555)099-4455';
		testProp.Number_of_Employees__c = 5;
		testProp.TPA_Firm_Name__c = 'TPA Firm 01';
		testProp.Company_Zip_Postal_Code__c = 12345;
		testProp.Company_State__c = 'California';
		testProp.Advisor_NPN__c = '12345';
		testProp.TPA_EIN__c = '222222222';
		testProp.Company_EIN__c = '111111111';
		testProp.Principal_Id__c = '1234567891';
		insert testProp;

		testProp.Principal_Opportunity_Stage__c = 'Committed';
		testProp.Financial_Professional_Role__c = 'IA';
		update testProp;
		Test.setMock(HttpCalloutMock.class, new SimplyCalloutMockFail());
		Test.startTest();
		SimplyCalloutBatch.start(7);
		SimplyCalloutBatch.start(0);
		Test.stopTest();
	}

}