force-app/main/default/objects/Picklist_Filter__mdt/Picklist_Filter__mdt.object-meta.xml
<CustomObject>
    <label>Picklist Filter</label>
    <pluralLabel>Picklist Filters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Picklist_Filter__mdt/fields/Filtered_Object__c.field-meta.xml
<CustomField>
    <fullName>Filtered_Object__c</fullName>
    <label>Filtered Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Picklist_Filters</relationshipLabel>
    <relationshipName>Picklist_Filters</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/PicklistFilterVizier_TEST.cls
@isTest
private class PicklistFilterVizier_TEST {

    @isTest
    private static void checkPicklistFilterCase() {
        test.startTest();
        List<Picklist_Filter__mdt> picklistFilterResults = PicklistFilterVizier.fetchObjectPicklistFilters('Case');
        test.stopTest();
        Picklist_Filter__mdt singleResult = picklistFilterResults.get(0);
        system.assert(singleResult != null, 'Should return something, good job.');
        system.assert(singleResult.Filtered_Object__c == 'Case', 'Specifically, it should return a record with the case object.');
    }

    @isTest
    private static void checkPicklistFilterNull() {
        test.startTest();
        List<Picklist_Filter__mdt> picklistFilterResults = PicklistFilterVizier.fetchObjectPicklistFilters('');
        test.stopTest();
        Picklist_Filter__mdt singleResult = picklistFilterResults.get(0);
        system.assert(singleResult != null, 'Should return something, good job.');
    }
}