force-app/main/default/objects/Picklist_Filter__mdt/Picklist_Filter__mdt.object-meta.xml
<CustomObject>
    <label>Picklist Filter</label>
    <pluralLabel>Picklist Filters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Picklist_Filter__mdt/fields/Filtered_Object__c.field-meta.xml
<CustomField>
    <fullName>Filtered_Object__c</fullName>
    <label>Filtered Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Picklist_Filters</relationshipLabel>
    <relationshipName>Picklist_Filters</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/PicklistFilterVizier.cls
public with sharing class PicklistFilterVizier {
    @AuraEnabled(cacheable=true)
    public static List <Picklist_Filter__mdt> fetchObjectPicklistFilters(String inputRecord) {

        List<Picklist_Filter__mdt> requestedPicklistFilters = new List<Picklist_Filter__mdt>();
        List<Picklist_Filter__mdt> allPicklistFilters = Picklist_Filter__mdt.getAll().values();

IF (inputRecord != '') {

        for(Integer i = 0; i < allPicklistFilters.size(); i++){
            if(allPicklistFilters[i].Filtered_Object__c == inputRecord){
                requestedPicklistFilters.add(allPicklistFilters[i]);
            }
        }
    } else {

        requestedPicklistFilters.addAll(allPicklistFilters);
    }
        return requestedPicklistFilters;
        }
}