force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PRP-{0000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Advisor_CRD__c.field-meta.xml
<CustomField>
    <fullName>Advisor_CRD__c</fullName>
    <label>Advisor CRD</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Advisor_NPN__c.field-meta.xml
<CustomField>
    <fullName>Advisor_NPN__c</fullName>
    <label>Advisor NPN</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Client_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Company_Name__c</fullName>
    <label>Client Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Company_EIN__c.field-meta.xml
<CustomField>
    <fullName>Company_EIN__c</fullName>
    <label>Company EIN</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Company_State__c.field-meta.xml
<CustomField>
    <fullName>Company_State__c</fullName>
    <label>Company State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Company_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Zip_Code__c</fullName>
    <formula>LPAD(TEXT(Company_Zip_Postal_Code__c), 5, &apos;0&apos; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Zip Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Company_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Zip_Postal_Code__c</fullName>
    <label>Company Zip/Postal Code</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Contact_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Phone_Number__c</fullName>
    <label>Contact Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Financial_Professional_Role__c.field-meta.xml
<CustomField>
    <fullName>Financial_Professional_Role__c</fullName>
    <description>This field has a corresponding field on Contact that is updated via flow. If you add/remove a value here, do the same for the Contact field.</description>
    <label>Financial Professional Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>IAR</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Firm_Name__c.field-meta.xml
<CustomField>
    <fullName>Firm_Name__c</fullName>
    <label>Firm Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Insurance_Agency_NPN__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Agency_NPN__c</fullName>
    <label>Insurance Agency NPN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Number_of_Employees__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Employees__c</fullName>
    <label>Number of Employees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Plan_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Effective_Date__c</fullName>
    <label>Plan Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Principal_Opportunity_Closed_Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Principal_Opportunity_Closed_Lost_Reason__c</fullName>
    <label>Principal Opportunity Closed Lost Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Case Not Taken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Principal_Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Principal_Opportunity_Id__c</fullName>
    <label>Principal Opportunity Id</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Principal_Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Principal_Opportunity_Stage__c</fullName>
    <label>Principal Opportunity Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Proposal / Price Quote</fullName>
            </value>
            <value>
                <fullName>Presentation</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Committed</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/TPA_EIN__c.field-meta.xml
<CustomField>
    <fullName>TPA_EIN__c</fullName>
    <label>TPA EIN</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/TPA_Firm_Name__c.field-meta.xml
<CustomField>
    <fullName>TPA_Firm_Name__c</fullName>
    <label>TPA Firm Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProposalsBatch__c/ProposalsBatch__c.object-meta.xml
<CustomObject>
    <label>ProposalsBatch</label>
    <nameField>
        <displayFormat>PB-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProposalsBatch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProposalsBatch__c/fields/Callout_Failed__c.field-meta.xml
<CustomField>
    <fullName>Callout_Failed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for determining which records failed during the callout.</description>
    <label>Callout Failed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProposalsBatch__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>ProposalsBatch</relationshipLabel>
    <relationshipName>ProposalsBatch</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProposalsBatch__c/fields/proposalId__c.field-meta.xml
<CustomField>
    <fullName>proposalId__c</fullName>
    <label>proposalId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SimplyCalloutBatchControl__c/SimplyCalloutBatchControl__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to control if SimplyCalloutBatch is currently running.</description>
    <label>SimplyCalloutBatchControl</label>
</CustomObject>

force-app/main/default/objects/SimplyCalloutBatchControl__c/fields/isBatchRunning__c.field-meta.xml
<CustomField>
    <fullName>isBatchRunning__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isBatchRunning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SimplyCalloutBatch.cls
public with sharing class SimplyCalloutBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable, Database.Stateful {

	private String originalTransactionId;

    public Database.QueryLocator start(Database.BatchableContext bc) {
		this.originalTransactionId = Logger.getTransactionId();
        SimplyCalloutBatchControl__c batchControl = SimplyCalloutBatchService.getOrCreateBatchControl();
		Logger.info('Starting SimplyCalloutBatch execution ' + this.originalTransactionId);

        if (batchControl.IsBatchRunning__c) {
			String txId = Logger.getTransactionId();
			Logger.warn('Skipping execution because batch is already running: ' + txId);
			Logger.saveLog();
			return Database.getQueryLocator('SELECT id from Proposal__c WHERE id = null');
		}
		batchControl.IsBatchRunning__c = true;
		update batchControl;

        Set<Id> proposalIdSet = new Set<Id>();
		List<ProposalsBatch__c> proposalsForUpdateList = [SELECT ProposalId__c FROM ProposalsBatch__c WHERE Callout_Failed__c = FALSE];
		for (ProposalsBatch__c proposalForUpdate : proposalsForUpdateList) {
			Id recordId = Id.valueOf(proposalForUpdate.ProposalId__c);
			proposalIdSet.add(recordId);
		}

		Logger.debug('Found ' + proposalIdSet.size() + ' proposals to process');
		Logger.saveLog();

		String query =
			'SELECT Id, Name, Client_Company_Name__c, ' +
			'Contact_Phone_Number__c,' +
			'Company_State__c,' +
			'Company_EIN__c,' +
			'Company_Zip_Code__c,' +
			'Plan_Effective_Date__c,' +
			'Number_of_Employees__c,' +
			'Advisor_NPN__c,' +
			'Advisor_CRD__c,' +
			'Firm_Name__c,' +
			'TPA_Firm_Name__c,' +
			'TPA_EIN__c,' +
			'Principal_Opportunity_Id__c,' +
			'Principal_Opportunity_Stage__c,' +
			'Principal_Opportunity_Closed_Lost_Reason__c,' +
			'Company_Zip_Postal_Code__c,' +
			'Financial_Professional_Role__c,' +
			'Insurance_Agency_NPN__c ' +
			'FROM Proposal__c ' +
			'WHERE Id IN : proposalIdSet';
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext bc, List<Proposal__c> proposalList) {
		Logger.setParentLogTransactionId(this.originalTransactionId);
		Logger.debug('Executing batch for ' + proposalList.size() + ' proposals');

		List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
		List<Proposal__c> proposalsToUpdate = new List<Proposal__c>();

		List<String> proccesedProposals = new List<String>();
		List<String> failedProposals = new List<String>();
		Map<Id, List<String>> failedProposalsMap = new Map<Id, List<String>>();

		String authKey;
		HttpResponse authResponse = SimplyCalloutBatchService.getSimplyAuthToken();

		Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(authResponse.getBody());
		authKey = (String) results.get('access_token');

		if (authResponse.getStatusCode() == 200) {
			Logger.info('Authentication successful');
			for (Proposal__c proposal : proposalList) {
				String jsonS = SimplyCalloutBatchService.getSimplyPayload(proposal);
				HttpResponse response = SimplyCalloutBatchService.sendSimplyCallout(jsonS, proposal, authKey);
				if (response.getStatusCode() == 200 || response.getStatusCode() == 201) {
					Proposal__c proposalForUpdate = SimplyCalloutBatchService.updateProposal(response, proposal);
					proposalsToUpdate.add(proposalForUpdate);
				} else {
					Logger.debug('JSON SENT: ' + jsonS);
					Logger.error(new LogMessage('SendSimplyCallout failed for proposal {0}, ' +
												'\n response status code: {1}' +
												'\n Response body: {2}',
												proposal.Id, response.getStatusCode(), response.getBody()).getMessage());
					Messaging.SingleEmailMessage errEmail = SimplyCalloutBatchService.sendErrorEmail(response, proposal);
					emailsToSend.add(errEmail);
					failedProposals.add(proposal.Id);
					failedProposalsMap.put(proposal.Id, new List<String>{ response.getBody(), String.valueOf(response.getStatusCode()) });
				}
			}

			List<Database.SaveResult> srpPoposalsToUpdate = Database.update(proposalsToUpdate, false);
			for (Database.SaveResult sr : srpPoposalsToUpdate) {
				if (sr.isSuccess()) {
					proccesedProposals.add(sr.getId());
				}
			}
			SimplyCalloutBatchService.proccessProposalBatch(proccesedProposals, failedProposals, failedProposalsMap);
		} else {
			// Messaging.sendEmail(emailsToSend);
			Logger.error(new LogMessage('Authentication failed, response status code: {0}' +
			'\n Response body: {1}',
			authResponse.getStatusCode(), authResponse.getBody()).getMessage());
		}
		Logger.saveLog();
	}

	public void finish(Database.BatchableContext bc) {
        SimplyCalloutBatchControl__c batchControl = [SELECT IsBatchRunning__c FROM SimplyCalloutBatchControl__c LIMIT 1];
        batchControl.IsBatchRunning__c = false;
        update batchControl;
	}

    public static void start(Integer mins) {
		string jobName = 'Simply Batch job - ';
		if (mins == 7) 
			Database.executeBatch(new SimplyCalloutBatch(), 5);
		else {
			jobName = jobName += mins + ' - ' + DateTime.now().format();
			String sch = '0 ' + String.valueOf(mins) + ' 5-18 ? * MON-FRI *';
			System.schedule(jobName, sch, new SimplyCalloutBatch());
		}
	}
	public void execute(SchedulableContext SC) {
		Database.executeBatch(new SimplyCalloutBatch(), 5);
	}
}

// SimplyCalloutBatch.start(0);
// SimplyCalloutBatch.start(15);
// SimplyCalloutBatch.start(30);
// SimplyCalloutBatch.start(45);