force-app/main/default/objects/Paradigm_Endpoint__mdt/Paradigm_Endpoint__mdt.object-meta.xml
<CustomObject>
    <label>Paradigm Endpoint</label>
    <pluralLabel>Paradigm Endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/Paradigm_Endpoint__mdt/fields/Auth_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Auth_Endpoint__c</fullName>
    <label>Auth Endpoint</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PRP-{0000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Errors__c.field-meta.xml
<CustomField>
    <fullName>Errors__c</fullName>
    <description>Populated with errors from Paradigm via Purchase API</description>
    <label>Errors</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ParadigmAuthController.cls
public with sharing class ParadigmAuthController {

    @AuraEnabled(cacheable=false)
    public static String getAuthToken(String propId) {

        Paradigm_Endpoint__mdt credential = [SELECT Auth_Endpoint__c,
                                                    Username__c,
                                                    Password__c,
                                                    isActive__c
                                            FROM Paradigm_Endpoint__mdt
                                            WHERE isActive__c = true
                                            LIMIT 1 ];

        String username = !Test.isRunningTest() ?  credential.Username__c : 'test';
        String password = !Test.isRunningTest() ?  credential.Password__c : 'test';
        String url = !Test.isRunningTest() ?  credential.Auth_Endpoint__c : 'https://api.paradigmtest.com/v1/auth/token';

        HttpRequest authRequest = new HttpRequest();
        authRequest.setEndpoint(url);
        authRequest.setMethod('POST');

        AuthRequest requestBody = new AuthRequest();
        requestBody.username = username;
        requestBody.password = password;
        String requestBodyJson = JSON.serialize(requestBody);
        authRequest.setHeader('Content-Type', 'application/json');
        authRequest.setBody(requestBodyJson);

        Http authHttp = new Http();
        HttpResponse authResponse = authHttp.send(authRequest);
        Map<String, Object> authResponseMap = (Map<String, Object>) JSON.deserializeUntyped(authResponse.getBody());

        AuthTokenResult result = new AuthTokenResult();

        if (authResponse.getStatusCode() == 200) {
            result.accessToken = (String) authResponseMap.get('accessToken');
            result.expiration = (String) authResponseMap.get('expiration');
            result.errorMessage = null;
            // ParadigmCalloutController.sendToParadigm(result.accessToken, propId);
        } else {
            Proposal__c prop = [SELECT Id, Errors__c FROM Proposal__c WHERE Id = :propId];
            prop.Errors__c = 'Error: ' + authResponse.getStatusCode() + ': \n' + authResponse.getStatus() + ' - ' + authResponse.getBody();
            update prop;
            result.errorMessage = 'Error: ' + authResponse.getStatusCode() + ': \n' + authResponse.getStatus() + ' - ' + authResponse.getBody();
            result.accessToken = null;
            result.expiration = null;
        }
        System.debug('result: ' + result);
        return JSON.serialize(result);
    }

    public class AuthTokenResult {
        @AuraEnabled
        public String accessToken { get; set; }
        @AuraEnabled
        public String expiration { get; set; }
        @AuraEnabled
        public String errorMessage { get; set; }
    }

    public class AuthRequest {
        public String username;
        public String password;
    }
}