force-app/main/default/objects/Invoice_Line_Items__c/Invoice_Line_Items__c.object-meta.xml
<CustomObject>
    <description>Line items linked to products/subscriptions that will be invoiced.</description>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Invoice Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Items__c/fields/Employee_Tier__c.field-meta.xml
<CustomField>
    <fullName>Employee_Tier__c</fullName>
    <description>Not synced, derived internally from product name</description>
    <label>Employee Tier</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Items__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Used by the Jitterbit integration and holds the Product Name from the NetSuite Invoice Line Item</description>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Items__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <description>Not synced, derived internally from product name</description>
    <label>Rate</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Items__c/fields/Service_Option__c.field-meta.xml
<CustomField>
    <fullName>Service_Option__c</fullName>
    <description>Not synced, derived internally from product name</description>
    <label>Service Option</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvoiceLineItemsTriggerHelper.cls
public with sharing class InvoiceLineItemsTriggerHelper {

    public static void parseProductName(List<Invoice_Line_Items__c> newInvoiceLineItems) {
        //Loop through inputs and call helper methods
        for (Invoice_Line_Items__c invoiceItem : newInvoiceLineItems) {
            if (invoiceItem.Product_Name__c != null) {
                if (invoiceItem.Service_Option__c == null) {
                    invoiceItem.Service_Option__c = InvoiceLineItemsTriggerHelper.getServiceOption(invoiceItem.Product_Name__c);
                }
                if (invoiceItem.Employee_Tier__c == null) {
                    invoiceItem.Employee_Tier__c = InvoiceLineItemsTriggerHelper.getEmployeeTier(invoiceItem.Product_Name__c);
                }
                if (invoiceItem.Rate__c == null) {
                    invoiceItem.Rate__c = InvoiceLineItemsTriggerHelper.getRate(invoiceItem.Product_Name__c);
                }
            }
        } 
    }

    private static String getServiceOption(String productName) {
        //Attempt to return a formatted service option from productName
        Pattern serviceOptionPattern = Pattern.compile('([A-Za-z]{1,})([( ][kK](?:[) ]|$))');    
        matcher serviceOptionMatch = serviceOptionPattern.matcher(productName);
        Boolean serviceOptionMatchFound = serviceOptionMatch.find();
        String newServiceOption;
        system.debug('service option match: ' + serviceOptionMatchFound);
        
        if (serviceOptionMatchFound) {
            newServiceOption = serviceOptionMatch.group(1).capitalize() + '(k)';
        } else {
            newServiceOption = InvoiceLineItemsTriggerHelper.getBadServiceOption(productName);
        }

        system.debug('new service option: ' + newServiceOption);
        return newServiceOption;
    }
        
    private static String getBadServiceOption(String productName) {
        //Specific checks for uniquely formatted service options
        String badServiceOption = null;

        if (productName.containsIgnoreCase('unbundled')) {
            badServiceOption = 'Simply Retirement Unbundled';
        } else if (productName.containsIgnoreCase('bundled')) {
            badServiceOption = 'Simply Retirement Bundled';
        } else if (productName.containsIgnoreCase('RKO')) {
            badServiceOption = 'RK Only';
        }
        return badServiceOption;
    }

    private static String getEmployeeTier(String productName) {
        //Attempt to return a formatted employee pricing tier from productName
        Pattern employeeTierPattern = Pattern.compile('(?:([0-9]{1,3}\\s?)-(\\s?[0-9]{1,3}))|([0-9]{1,}\\s?[+])');
        matcher employeeTierMatch = employeeTierPattern.matcher(productName);
        Boolean employeeMatchFound = employeeTierMatch.find();
        String newEmployeeTier = null;
        system.debug('employee match: ' + employeeMatchFound);

        if (employeeMatchFound) {
            if (!String.isBlank(employeeTierMatch.group(3))) {
                newEmployeeTier = employeeTierMatch.group(3);
            } else if (!String.isBlank(employeeTierMatch.group(1)) && !String.isBlank(employeeTierMatch.group(2))) {
                newEmployeeTier = employeeTierMatch.group(1) + '-' + employeeTierMatch.group(2);
            }
        }

        system.debug('new employee tier: ' + newEmployeeTier);
        return newEmployeeTier;
    }

    private static String getRate(String productName) {
        //Attempt to return a formatted rate from productName
        String newRate = null;

        if (productName.containsIgnoreCase('annual')) {
            newRate = 'Annual';
        } else if (productName.containsIgnoreCase('quarter')) {
            newRate = 'Quarterly';
        } else if (productName.containsIgnoreCase('month')) {
            newRate = 'Monthly';
        } else if (productName.containsIgnoreCase('week')) {
            newRate = 'Weekly';
        }

        system.debug('new rate: ' + newRate);
        return newRate;
    }
}